import type { Copy } from "./en";

const de: Copy = {
  meta: {
    title: "Splitea fürs iPhone: Rechnung teilen, auf den Cent genau",
    description: "Rechnung mit Freunden centgenau teilen: Beleg fotografieren, antippen, wer was hatte, Link schicken. Freunde wählen ihre Artikel im Browser, ohne App.",
    ogTitle: "Splitea: Rechnung teilen, auf den Cent genau",
    ogDescription: "Beleg fotografieren, antippen, wer was hatte, Link schicken. Freunde wählen ihre Artikel in jedem Browser. Fürs iPhone.",
    ogImageAlt: "Rechnung teilen, auf den Cent genau. Der Bildschirm „Artikel zuweisen“ von Splitea auf einem iPhone mit den Hinweisen „1 Wähl einen Kontakt“ und „2 Tipp seine Artikel an“.",
    ogTagline: "Fürs iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "So geht’s" },
      { id: "trips", label: "Reisen" },
      { id: "abroad", label: "Ausland" },
      { id: "privacy", label: "Datenschutz" },
      { id: "pricing", label: "Preise" },
    ],
    cta: "Splitea laden",
    dismiss: "Ausblenden",
    qrLine: "Scanne mit deiner iPhone-Kamera, um Splitea zu laden.",
    qrLink: "Seite im App Store öffnen",
  },
  hero: {
    titleTop: "Rechnung teilen,",
    titleBottom: "auf den [[Cent]] genau.",
    tagline: "Jeder Cent an seinem Platz",
    body: "Fotografiere den Beleg, tippe an, wer was hatte, und schicke den Link. Freunde wählen ihre Artikel in jedem Browser aus und zahlen dir ihren Anteil zurück. Die App brauchen sie nicht.",
    noteTop: "Kostenloser Download.",
    noteBottom: "Fürs iPhone mit iOS 26 oder neuer.",
    android: "Du hast Android? Splitea-Links öffnen sich direkt in deinem Browser. Die App gibt es nur fürs iPhone.",
    pills: ["Wähl einen Kontakt", "Tipp seine Artikel an"],
    tryIt: "Live ausprobieren",
    done: "Fertig",
    demoLabel: "Live-Demo · die Seite, die deine Freunde öffnen",
    demoNote: "Das Handy ist live. Genau diese Seite öffnen deine Freunde.",
    qrCaption: "Am Computer? Scanne mit deiner iPhone-Kamera.",
  },
  how: {
    title: "Knipsen, tippen, teilen.\n[[Geld]] einsammeln.",
    tagline: "Scannen · Zuweisen · Steuer · Quitt",
    body: "Fotografiere die Rechnung, tippe an, wer was hatte, und Splitea rechnet Steuer, Trinkgeld und jeden Cent aus. Dann zahlen dir deine Freunde ihren Anteil zurück, ganz wie sie wollen.",
    steps: [
      {
        rail: "Scannen",
        title: "Knips den [[Beleg]].",
        body: "Splitea liest Artikel und Preise für dich aus. Verdecken Spiegelungen oder Unschärfe einen Preis, sagt dir die Kamera Bescheid.",
        tagline: "Kamera · Fotos · PDF",
      },
      {
        rail: "Zuweisen",
        title: "Wähl einen Kontakt.\nTipp seine [[Artikel]] an.",
        body: "Geteilte Gerichte werden auf alle aufgeteilt, die mitgegessen haben, und mit einem Tipp geht ein Artikel an alle.",
        tagline: "Wer hatte was",
      },
      {
        rail: "Steuern",
        title: "[[Lokale]] Steuern, automatisch.",
        body: "Jeder Artikel bekommt seinen eigenen Steuersatz, abgeglichen mit der Steuer auf dem Beleg. Hier: 7 % auf den Mofongo, 11,5 % auf den Old Fashioned.",
        tagline: "Schluss mit Kopfrechnen",
      },
      {
        rail: "Begleichen",
        title: "Alle quitt, ganz [[einfach]].",
        body: "Freunde tippen auf „Zahlen“, und Venmo, PayPal oder Cash App öffnet sich mit ihrem Betrag. Das Geld läuft nie über Splitea.",
        tagline: "Anfordern · Kassieren · Nochmal",
      },
    ],
    pills: {
      contact: "Wähl einen Kontakt",
      items: "Tipp seine Artikel an",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "Über jede App anfordern",
      paid: "Deine Apps, ihre Wahl",
    },
    stepGo: (n: number, label: string) => `Zu Schritt ${n}: ${label}`,
    play: "Demo abspielen",
    pause: "Demo pausieren",
    videoLabel: "Artikel zuweisen: Tippe auf einen Kontakt und dann auf die Artikel, die diese Person hatte.",
    endTitle: "Probier es beim nächsten Essen aus.",
    endNote: "Kostenloser Download.",
  },
  send: {
    title: "Teil den [[Link]],\nsie haken ab.",
    tagline: "Keine App · Kein Konto für Freunde",
    body: "Teile einen Live-Link über Nachrichten, WhatsApp oder Mail, mit einer Splitea-Vorschaukarte. Freunde öffnen ihn in jedem Browser, auch auf Android, und tippen an, was sie hatten. Alle mit dem Link sehen jede Auswahl in Echtzeit, und wenn du fertig bist, kannst du die Bearbeitung sperren.",
    line: "Das Handy ganz oben zeigt genau die Seite, die deine Freunde öffnen.",
    tryIt: "Ausprobieren",
    connected: "Verbunden (3)",
    anyBrowser: "Öffnet sich in jedem Browser",
    cardAlt: "Eine Splitea-Linkvorschau in einem Chat.",
  },
  trips: {
    title: "Eine [[Reise]].\nEin Beleg.",
    tagline: "Gruppieren · Teilen · Abrechnen",
    body: "Leg die Belege einer Reise in einen Ordner. Die Ordnerübersicht rechnet für jede Person die Summe über alle Splits zusammen und erkennt dieselbe Person auch dann, wenn ihre Nummer unterschiedlich gespeichert ist. Mit „Ordner exportieren“ teilst du dann ein einziges PDF mit den Summen aller.",
    alt: "Ein Reiseordner mit mehreren Belegen.",
  },
  digital: {
    title: "[[Digitaler]] Beleg?\nNoch einfacher.",
    tagline: "Safari · Teilen · Splitea",
    body: "Hast du den Beleg als Webseite oder PDF? Teile ihn aus Safari, Dateien oder Mail und wähle Splitea. Webseiten werden vor dem Auslesen zu einem PDF mit echtem Text. Braucht die Seite eine Anmeldung, nutze die PDF-Option von Safari.",
    pills: ["Tipp auf Teilen", "Wähl Splitea"],
    alt: "Das Teilen-Menü von iOS mit Splitea in der Reihe der Apps.",
  },
  abroad: {
    title: "Fremde Währung?\nTeile in [[deiner]].",
    tagline: "Umrechnen · Übersetzen · Abrechnen",
    body: "Rechne einen Split in deine eigene Währung um, mit dem Betrag auf deiner Kartenabrechnung, deinem eigenen Kurs oder dem heutigen Marktkurs. Die umgerechneten Anteile ergeben weiterhin genau die umgerechnete Summe, und Freunde sehen den Kurs auf ihrer Seite. Währungen ohne Cent, wie Yen und Won, funktionieren auch.",
    translateBefore: "Artikelnamen in einer anderen Schrift bekommen eine Übersetzung in deine Sprache, etwa ",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: " (Bibimbap). Die App spricht 10 Sprachen.",
    alt: "Das Fenster zur Währungsumrechnung, von Pesos in Dollar.",
    payTitle: "Freunde zahlen mit der App, die sie schon nutzen.",
    regions: [
      { title: "USA", text: "Venmo, Cash App, PayPal, Revolut und ATH Móvil. Venmo öffnet sich mit Betrag und Notiz bereits ausgefüllt." },
      { title: "Puerto Rico", text: "ATH Móvil, Venmo, Cash App, PayPal und Revolut. Bei ATH Móvil gibt dein Freund den Betrag selbst ein." },
      { title: "Großbritannien und Irland", text: "Monzo, Revolut und PayPal, mit bereits ausgefülltem Betrag." },
      { title: "Europa", text: "Revolut und PayPal, mit bereits ausgefülltem Betrag." },
      { title: "Indien", text: "Google Pay UPI in Rupien, mit bereits ausgefülltem Betrag." },
    ],
    prev: "Vorherige Region",
    next: "Nächste Region",
    footnote: "PayPal funktioniert in den meisten Ländern. Keine Zahlungs-App eingerichtet? Freunde können ihren Anteil trotzdem als bezahlt markieren. Apple Pay, Apple Cash und Zelle werden nicht unterstützt.",
  },
  privacy: {
    title: "Deine Belege.\nDeine [[iCloud]].",
    tagline: "Werbefrei · Kein Tracking · iCloud",
    body: "Gespeicherte Splits, Ordner und dein Profil werden über deine eigene iCloud synchronisiert, und die Server von Splitea speichern deine Belegsammlung nicht. Kontaktfotos bleiben auf deinem iPhone, und ein Name verlässt es nur, wenn du einen Split teilst, in dem diese Person vorkommt. Was dein iPhone trotzdem verlässt, steht hier.",
    facts: [
      {
        title: "Ausgelesen, nicht behalten.",
        text: "Zum Auslesen eines Belegs geht das Foto an den Server von Splitea und an ein KI-Modell (derzeit Google Gemini). Der Scan-Dienst behält das Foto nicht. Zu jedem Scan speichert er einen Eintrag mit deinem Konto, der App- und iOS-Version und dem Land. Wenn du den Standortzugriff erlaubst, wird ein ungefährer Standort als Hinweis auf den örtlichen Steuersatz mitgesendet.",
      },
      {
        title: "Links laufen nach 30 Tagen ab.",
        text: "Wenn du einen Split teilst, geht eine Kopie an den Freigabeserver von Splitea: die Artikel und Beträge, das Belegfoto, die Namen und Telefonnummern der Personen darin und deine Zahlungs-Benutzernamen. Der Link läuft 30 Tage nach dem Teilen ab.",
      },
      {
        title: "Keine Werbung. Kein Tracking.",
        text: "Die App enthält keine Werbung, keine Tracking-SDKs und keine Code-Bibliotheken von Drittanbietern. Unsere Webseiten zählen Besuche nur mit Cloudflare Web Analytics, ohne Cookies.",
      },
      {
        title: "Dein Profil, bis du es löschst.",
        text: "Dein Name, dein Profilfoto, deine Telefonnummer, deine E-Mail-Adresse und deine Zahlungs-Benutzernamen liegen auf den Servern von Splitea, damit Freunde dich finden und bezahlen können, und die App gleicht die Telefonnummern in deinen Splits mit diesen Profilen ab. Wenn du dein Konto in den Einstellungen löschst, endet das Teilen deiner Splits, das Profil wird entfernt, und deine Belege werden von deinem iPhone und aus deiner iCloud gelöscht.",
      },
    ],
    link: "Datenschutzrichtlinie lesen",
  },
  pricing: {
    title: "Starte mit [[3]] kostenlosen Scans.",
    tagline: "Kostenlos laden · 3 Gratis-Scans",
    body: "Splitea kannst du kostenlos herunterladen, und jedes Konto bekommt 3 kostenlose Scans: 3 insgesamt, nicht 3 pro Monat. Danach brauchst du Splitea Unlimited, um einen neuen Beleg hinzuzufügen, egal ob du ihn scannst, ein Foto oder PDF importierst, ihn aus einer anderen App teilst oder von Hand eintippst. Aufteilen, Links teilen, Live-Bearbeitung, Begleichen, Ordner, PDF-Export und Währungsumrechnung sind ohne Abo nutzbar. Einen Link zu öffnen ist für deine Freunde immer kostenlos.",
    plan: "Splitea Unlimited",
    checks: ["Unbegrenzt viele Belege, gescannt, importiert oder eingetippt", "Eigene Akzentfarbe"],
    price: (monthly: string, yearly: string) => `${monthly} im Monat oder ${yearly} im Jahr in den USA.`,
    vary: "Die Preise sind je nach Land unterschiedlich.",
    fine: "Schlägt das Auslesen fehl, wird kein Scan verbraucht, und dasselbe Foto noch einmal zu scannen zählt nicht doppelt.",
  },
  faq: {
    title: "Fragen und [[Antworten]].",
    items: [
      {
        q: "Brauchen meine Freunde Splitea oder ein iPhone?",
        a: "Nein. Dein Link öffnet sich in jedem Browser, auch auf Android-Handys und Laptops, ohne App und ohne Konto. Die Seite gibt es in 10 Sprachen, und deine Freunde zahlen mit ihrer eigenen Zahlungs-App.",
      },
      {
        q: "Brauche ich ein Konto?",
        a: "Ja. Zum Scannen und Teilen meldest du dich mit Apple an, und Splitea fragt nach Zugriff auf deine Kontakte, damit du Personen auswählen kannst. Voller und eingeschränkter Zugriff funktionieren beide.",
      },
      {
        q: "Was kann ich ohne Abo machen?",
        a: "Alles mit den Belegen, die du schon hast. Links teilen, Live-Bearbeitung, Begleichen, Ordner, PDF-Export und Währungsumrechnung sind ohne Abo nutzbar, genauso wie Splits, die dir Freunde schicken. Nach deinen 3 kostenlosen Scans brauchst du Splitea Unlimited, um einen neuen Beleg hinzuzufügen, egal ob per Kamera, Foto, PDF, Teilen-Menü oder von Hand. Das Abo schaltet außerdem eine eigene Akzentfarbe frei.",
      },
      {
        q: "Wickelt Splitea das Geld ab?",
        a: "Nein. Splitea bewegt nie Geld. Es öffnet die Zahlungs-App oder den Zahlungslink deines Freundes: je nach Land Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo oder Google Pay UPI. Jede öffnet sich mit bereits ausgefülltem Betrag, außer ATH Móvil, wo dein Freund ihn selbst eingibt. Apple Pay, Apple Cash und Zelle werden nicht unterstützt, aber Freunde können ihren Anteil trotzdem als bezahlt markieren.",
      },
      {
        q: "Was, wenn ein Beleg falsch ausgelesen wird?",
        a: "Splitea gleicht Zwischensumme, Steuer und Gesamtbetrag mit dem gedruckten Beleg ab und warnt dich, wenn sie nicht übereinstimmen. Tippe auf einen Artikel, um Beschreibung, Preis oder Steuer zu ändern. Die Kamera sagt dir außerdem, wenn ein Foto Spiegelungen zeigt oder unscharf ist, den Beleg abschneidet, eine Speisekarte statt der Rechnung zeigt oder mehrere Belege enthält.",
      },
      {
        q: "Funktioniert es außerhalb der USA?",
        a: "Ja. Splitea gibt es im App Store in vielen Ländern, darunter Großbritannien, Mexiko, Japan, Deutschland, Indien, Brasilien und Südkorea. Es teilt in der Währung des Belegs, auch in Währungen ohne Cent wie Yen und Won, kommt mit Belegen zurecht, in denen die Steuer schon enthalten ist, wie in Japan und in der EU, und kann einen Split in deine eigene Währung umrechnen.",
      },
      {
        q: "iOS 27 kann Rechnungen teilen. Warum Splitea?",
        a: "Apples eigene Funktion zum Teilen von Rechnungen ist eingebaut und kostenlos. Sie läuft über Apple Cash, das es in den 50 US-Bundesstaaten, in DC und in Puerto Rico für Einwohner der USA ab 18 Jahren mit iPhone, iPad oder Apple Watch gibt. Mit Splitea öffnen Freunde deinen Link auf jedem Handy oder Computer und zahlen mit Apps wie Venmo, PayPal oder ATH Móvil. Splitea funktioniert in vielen Ländern, und zum Scannen ist Apple Intelligence nicht nötig. Jeder Freund wählt seine Artikel live selbst aus, jeder Artikel bekommt seine lokale Steuer, und die Belege einer Reise werden in einem PDF zusammengerechnet. Bei Splitea hast du 3 kostenlose Scans, danach brauchst du ein Abo.",
      },
      {
        q: "Wie lange sind geteilte Links gültig?",
        a: "Geteilte Links laufen 30 Tage nach dem Teilen ab. Deine eigene Kopie bleibt in deiner Sammlung.",
      },
      {
        q: "Auf welchen iPhones läuft es?",
        a: "Auf jedem iPhone mit iOS 26 oder neuer. Es gibt keine App für iPad, Mac oder Android, deshalb nutzen Freunde mit anderen Geräten den Link im Browser.",
      },
    ],
    dataQ: "Wo sind meine Daten?",
    dataBefore: "Gespeicherte Belege, Ordner und dein Profil werden über deine eigene iCloud synchronisiert. Im Abschnitt ",
    dataLink: "Datenschutz",
    dataAfter: " weiter oben steht, was an die Server von Splitea geht und wie lange es dort bleibt.",
  },
  get: {
    pronunciation: "/ spli·TEH·a /",
    title: "Jeder Beleg, [[einen Tipp]] weg.",
    body: "Jeder Split, den du speicherst, bleibt in deiner Sammlung und wird über deine eigene iCloud synchronisiert. Öffne einen, um zu sehen, wer schon bezahlt hat.",
    small: "Kostenloser Download mit 3 Gratis-Scans. Nur fürs iPhone, iOS 26 oder neuer.",
    qrCaption: "Am Computer? Scanne mit deiner iPhone-Kamera.",
    tagline: "Splitea · Deine Rechnung, erledigt",
    gridAlt: "Die Sammlung „Alle Splits“.",
    listAlt: "Die Sammlung „Alle Splits“ als Liste.",
  },
  footer: {
    origin: "Splitea · Entwickelt in Puerto Rico",
    languages: "Sprache",
    privacy: "Datenschutz",
    terms: "Nutzungsbedingungen",
    appStore: "App Store",
    legal: [
      "Apple, das Apple Logo, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash und Apple Intelligence sind Marken der Apple Inc., die in den USA und weiteren Ländern und Regionen eingetragen sind. App Store ist eine Dienstleistungsmarke der Apple Inc.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp und Zelle sind Marken ihrer jeweiligen Inhaber. Splitea steht in keiner Verbindung zu ihnen.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "Splitea im App Store laden",
};

export default de;
