export const en = {
  meta: {
    title: "Splitea for iPhone: split receipts with friends, to the cent",
    description: "Snap the receipt, tap who had what, and send one link. Friends pick their items in any browser with no app, and every share adds up to the exact total.",
    ogTitle: "Splitea: split the bill to the last cent",
    ogDescription: "Snap the receipt, tap who had what, send a link. Friends pick their items in any browser. For iPhone.",
    ogImageAlt: "Split the bill to the last cent. Splitea's Assign Items screen on an iPhone with the callouts 1 Tap a contact and 2 Tap their items.",
    ogTagline: "For iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "How it works" },
      { id: "trips", label: "Trips" },
      { id: "abroad", label: "Abroad" },
      { id: "privacy", label: "Privacy" },
      { id: "pricing", label: "Pricing" },
    ],
    cta: "Get Splitea",
    dismiss: "Dismiss",
    qrLine: "Scan with your iPhone camera to get Splitea.",
    qrLink: "Open the App Store page",
  },
  hero: {
    titleTop: "Split the bill",
    titleBottom: "to the last [[cent]].",
    tagline: "Every cent accounted for",
    body: "Snap the receipt, tap who had what, and send the link. Friends pick their items in any browser and pay you back. They don't need the app.",
    noteTop: "Free to download.",
    noteBottom: "For iPhone with iOS 26 or later.",
    android: "On Android? Splitea links open right in your browser. The app is for iPhone.",
    pills: ["Tap a contact", "Tap their items"],
    tryIt: "Try it live",
    done: "Done",
    demoLabel: "Live demo · the page your friends open",
    demoNote: "That phone is live. It's the exact page your friends open.",
    qrCaption: "On a computer? Scan with your iPhone camera.",
  },
  how: {
    title: "Snap, tap, send.\nGet [[paid]] back.",
    tagline: "Scan · Assign · Tax · Settle",
    body: "Snap the bill, tap who had what, and Splitea works out tax, tip and every cent. Then friends pay you back their way.",
    steps: [
      {
        rail: "Scan",
        title: "Snap the [[receipt]].",
        body: "Splitea reads the items and prices for you. If glare or blur hides a price, the camera tells you.",
        tagline: "Camera · Photos · PDF",
      },
      {
        rail: "Assign",
        title: "Tap a contact.\nTap their [[items]].",
        body: "Shared plates split between whoever had them, and one tap gives an item to everyone.",
        tagline: "Who had what",
      },
      {
        rail: "Taxes",
        title: "[[Local]] taxes, automatic.",
        body: "Each item gets its own rate, checked against the printed tax. Here: 7% on the mofongo, 11.5% on the Old Fashioned.",
        tagline: "No more napkin math",
      },
      {
        rail: "Settle",
        title: "Settle up, [[simply]].",
        body: "Friends tap Pay to open Venmo, PayPal or Cash App with their amount. Splitea never touches the money.",
        tagline: "Request · Reimburse · Repeat",
      },
    ],
    pills: {
      contact: "Tap a contact",
      items: "Tap their items",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "Request in any app",
      paid: "Get paid their way",
    },
    stepGo: (n: number, label: string) => `Go to step ${n}: ${label}`,
    play: "Play the demo",
    pause: "Pause the demo",
    videoLabel: "Assigning items: tap a contact, then tap the items they had.",
    endTitle: "Try it at your next dinner.",
    endNote: "Free to download.",
  },
  send: {
    title: "Send the [[link]].\nThey pick.",
    tagline: "No app · No signup for friends",
    body: "Share one live link in Messages, WhatsApp or Mail, with a Splitea preview card. Friends open it in any browser, Android included, and tap what they had. Everyone with the link sees each pick as it happens, and you can lock editing when you're done.",
    line: "The phone at the top of this page is that page.",
    tryIt: "Try it",
    connected: "Connected (3)",
    anyBrowser: "Opens in any browser",
    cardAlt: "A Splitea link preview card in a chat.",
  },
  trips: {
    title: "One [[trip]].\nOne summary.",
    tagline: "Group · Export · Settle",
    body: "Put a trip's receipts in a folder. Folder Summary adds up each person's total across every split, and matches the same person even when their number is saved differently. Then Export Folder shares one PDF with everyone's totals.",
    alt: "A trip folder holding several receipts.",
  },
  digital: {
    title: "[[Digital]] receipt?\nEven easier.",
    tagline: "Safari · Share · Splitea",
    body: "Got the receipt as a web page or a PDF? Share it from Safari, Files or Mail and choose Splitea. Web pages become a PDF with real text before they're read. If the page needs a login, use Safari's PDF option.",
    pills: ["Tap Share", "Choose Splitea"],
    alt: "The iOS share sheet with Splitea in the app row.",
  },
  abroad: {
    title: "Foreign bill?\nSplit in [[yours]].",
    tagline: "Convert · Translate · Settle",
    body: "Convert a split into your home currency using the amount on your card statement, your own rate, or today's market rate. Converted shares still add up to the converted total, and friends see the rate on their page. Currencies without cents, like yen and won, work too.",
    translateBefore: "Item names in another script come with a translation in your language, like ",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: " (Bibimbap). The app speaks 10 languages.",
    alt: "The currency conversion sheet, from pesos to dollars.",
    payTitle: "Friends pay with the app they already use.",
    regions: [
      { title: "United States", text: "Venmo, Cash App, PayPal, Revolut and ATH Móvil. Venmo opens with the amount and a note filled in." },
      { title: "Puerto Rico", text: "ATH Móvil, Venmo, Cash App, PayPal and Revolut. With ATH Móvil, your friend types the amount." },
      { title: "UK and Ireland", text: "Monzo, Revolut and PayPal, with the amount filled in." },
      { title: "Europe", text: "Revolut and PayPal, with the amount filled in." },
      { title: "India", text: "Google Pay UPI in rupees, with the amount filled in." },
    ],
    prev: "Previous region",
    next: "Next region",
    footnote: "PayPal works in most countries. No payment app set up? Friends can still mark their share as paid. Apple Pay, Apple Cash and Zelle aren't supported.",
  },
  privacy: {
    title: "Your receipts.\nYour [[iCloud]].",
    tagline: "No ads · No trackers · Your iCloud",
    body: "Saved splits, folders and your profile sync through your own iCloud, and Splitea's servers don't hold your receipt library. Contact photos stay on your iPhone, and a name only leaves it when you share a split with that person in it. Here is what does leave it.",
    facts: [
      {
        title: "Read, not kept.",
        text: "To read a receipt, the photo goes to Splitea's server and an AI model (currently Google Gemini). The scan service doesn't keep the image. It keeps a record of each scan with your account, app and iOS version, and country. If you allow location, an approximate location goes along to pick the tax rate.",
      },
      {
        title: "Links expire after 30 days.",
        text: "When you share a split, a copy goes to Splitea's share server: the items and amounts, the receipt photo, the names and phone numbers of the people in it, and your payment usernames. The link expires 30 days after you create it.",
      },
      {
        title: "No ads. No trackers.",
        text: "The app has no ads, no tracking SDKs and no third-party packages. Our web pages only count visits, using Cloudflare Web Analytics without cookies.",
      },
      {
        title: "Your profile, until you delete it.",
        text: "Your name, photo, phone number, email and payment usernames are kept on Splitea's servers so friends can find and pay you, and the app checks the phone numbers in your splits against them. Deleting your account in Settings ends your shares, removes that profile, and erases your receipts from your iPhone and iCloud.",
      },
    ],
    link: "Read the privacy policy",
  },
  pricing: {
    title: "Start with [[3]] free scans.",
    tagline: "Free to download · 3 free scans",
    body: "Splitea is free to download, and every account gets 3 free scans: 3 in total, not 3 a month. After that, adding a new receipt needs Splitea Unlimited, whether you scan it, import a photo or PDF, share it in, or type it by hand. Splitting, sharing links, live editing, settling up, folders, PDF export and currency conversion have no paywall. Opening a link is always free for your friends.",
    plan: "Splitea Unlimited",
    checks: ["Unlimited receipts, scanned, imported or typed in", "Custom accent color"],
    price: (monthly: string, yearly: string) => `${monthly} a month or ${yearly} a year in the US.`,
    vary: "Prices vary by country.",
    fine: "A read that fails doesn't use up a scan, and scanning the same photo again isn't charged twice.",
  },
  faq: {
    title: "Questions, [[answered]].",
    items: [
      {
        q: "Do my friends need Splitea or an iPhone?",
        a: "No. Your link opens in any browser, on Android phones and laptops too, with no app and no account. The page comes in 10 languages, and they pay with their own payment app.",
      },
      {
        q: "Do I need an account?",
        a: "Yes. You sign in with Apple to scan and share, and Splitea asks for Contacts access so you can pick people. Full or limited access both work.",
      },
      {
        q: "What can I do without subscribing?",
        a: "Everything with the receipts you already have. Sharing links, live editing, settling up, folders, PDF export and currency conversion have no paywall, and neither do splits friends send you. After your 3 free scans, adding a new receipt, by camera, photo, PDF, share sheet or by hand, needs Splitea Unlimited, which also unlocks a custom accent color.",
      },
      {
        q: "Does Splitea handle the money?",
        a: "No. Splitea never moves money. It opens your friend's payment app or link: Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo or Google Pay UPI, depending on your country. Each opens with the amount filled in, except ATH Móvil, where your friend types it. Apple Pay, Apple Cash and Zelle aren't supported, but friends can still mark their share as paid.",
      },
      {
        q: "What if a receipt is read wrong?",
        a: "Splitea checks its subtotal, tax and total against the printed receipt and warns you when they don't match. Tap any item to change its description, price or tax. The camera also tells you when a photo has glare or blur, cuts off the receipt, shows a menu instead of the bill, or holds several receipts.",
      },
      {
        q: "Does it work outside the US?",
        a: "Yes. Splitea is on the App Store in many countries, including the UK, Mexico, Japan, Germany, India, Brazil and Korea. It splits in the receipt's currency, including ones without cents like yen and won, handles receipts with tax already included, like those in Japan and the EU, and can convert a split to your home currency.",
      },
      {
        q: "iOS 27 can split bills. Why use Splitea?",
        a: "Apple's Split Bill is built in and free. It runs on Apple Cash, which works in the 50 US states, DC and Puerto Rico for US residents 18 or older with an iPhone, iPad or Apple Watch. With Splitea, friends open your link on any phone or computer and pay with apps like Venmo, PayPal or ATH Móvil, it works in many countries, and scanning doesn't need Apple Intelligence. Each friend picks their own items live, every item gets its local tax, and a trip's receipts add up in one PDF. Splitea gives you 3 free scans, then needs a subscription.",
      },
      {
        q: "How long do share links last?",
        a: "Share links expire 30 days after you create them. Your own copy stays in your library.",
      },
      {
        q: "Which iPhones does it run on?",
        a: "Any iPhone with iOS 26 or later. There's no iPad, Mac or Android app, so friends on other devices use the link in their browser.",
      },
    ],
    dataQ: "Where is my data?",
    dataBefore: "Saved receipts, folders and your profile sync through your own iCloud. The ",
    dataLink: "privacy section",
    dataAfter: " above lists what goes to Splitea's servers and for how long.",
  },
  get: {
    pronunciation: "/ split·EH·ah /",
    title: "Every receipt, [[one tap]] away.",
    body: "Every split you save stays in your library, synced through your own iCloud. Open one to see who has paid.",
    small: "Free to download, with 3 free scans. iPhone only, iOS 26 or later.",
    qrCaption: "On a computer? Scan with your iPhone camera.",
    tagline: "Splitea · Your bill, sorted",
    gridAlt: "The All Splits library.",
    listAlt: "The All Splits library as a list.",
  },
  footer: {
    origin: "Splitea · Made in Puerto Rico",
    languages: "Language",
    privacy: "Privacy",
    terms: "Terms",
    appStore: "App Store",
    legal: [
      "Apple, the Apple logo, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash and Apple Intelligence are trademarks of Apple Inc., registered in the U.S. and other countries and regions. App Store is a service mark of Apple Inc.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp and Zelle are trademarks of their respective owners. Splitea isn't affiliated with them.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "Download Splitea on the App Store",
};

export type Copy = typeof en;
