import type { Copy } from "./en";

const es: Copy = {
  meta: {
    title: "Splitea para iPhone: divide la cuenta con amigos al centavo",
    description: "Tómale una foto al recibo, toca quién pidió qué y envía un enlace. Tus amigos eligen lo suyo en cualquier navegador, sin app, y todo cuadra al centavo.",
    ogTitle: "Splitea: divide la cuenta al centavo",
    ogDescription: "Tómale una foto al recibo, toca quién pidió qué y envía un enlace. Tus amigos eligen lo suyo en cualquier navegador. Para iPhone.",
    ogImageAlt: "Divide la cuenta al centavo. La pantalla Asignar artículos de Splitea en un iPhone con las indicaciones 1 Toca un contacto y 2 Toca sus artículos.",
    ogTagline: "Para iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "Cómo funciona" },
      { id: "trips", label: "Viajes" },
      { id: "abroad", label: "En el extranjero" },
      { id: "privacy", label: "Privacidad" },
      { id: "pricing", label: "Precios" },
    ],
    cta: "Obtener Splitea",
    dismiss: "Cerrar",
    qrLine: "Escanea con la cámara de tu iPhone para obtener Splitea.",
    qrLink: "Abrir la página del App Store",
  },
  hero: {
    titleTop: "Divide la cuenta",
    titleBottom: "al [[centavo]].",
    tagline: "Cada centavo en su lugar",
    body: "Tómale una foto al recibo, toca quién pidió qué y envía el enlace. Tus amigos eligen sus artículos en cualquier navegador y te devuelven el dinero. No necesitan la app.",
    noteTop: "Descarga gratuita.",
    noteBottom: "Para iPhone con iOS 26 o posterior.",
    android: "¿Usas Android? Los enlaces de Splitea se abren directamente en tu navegador. La app es para iPhone.",
    pills: ["Toca un contacto", "Toca sus artículos"],
    tryIt: "Pruébalo en vivo",
    done: "Listo",
    demoLabel: "Demo en vivo · la página que abren tus amigos",
    demoNote: "Ese teléfono está en vivo. Es la misma página que abren tus amigos.",
    qrCaption: "¿Estás en una computadora? Escanea con la cámara de tu iPhone.",
  },
  how: {
    title: "Escanea, toca, envía.\nY te [[pagan]].",
    tagline: "Escanear · Asignar · Impuestos · Saldar",
    body: "Tómale una foto a la cuenta, toca quién pidió qué y Splitea calcula el impuesto, la propina y cada centavo. Luego tus amigos te devuelven el dinero como prefieran.",
    steps: [
      {
        rail: "Escanear",
        title: "Escanea el [[recibo]].",
        body: "Splitea lee los artículos y los precios por ti. Si por un reflejo o una foto borrosa no se ve un precio, la cámara te avisa.",
        tagline: "Cámara · Fotos · PDF",
      },
      {
        rail: "Asignar",
        title: "Toca un contacto.\nToca sus [[artículos]].",
        body: "Los platos compartidos se dividen entre quienes los pidieron, y con un toque asignas un artículo a todos.",
        tagline: "Quién pidió qué",
      },
      {
        rail: "Impuestos",
        title: "Impuestos [[locales]], automáticos.",
        body: "Cada artículo recibe su propia tasa, que se compara con el impuesto impreso. Aquí: 7% para el mofongo y 11.5% para el Old Fashioned.",
        tagline: "Cero cálculos a mano",
      },
      {
        rail: "Saldar",
        title: "Todo saldado, [[fácilmente]].",
        body: "Tus amigos tocan Pagar para abrir Venmo, PayPal o Cash App con su monto. Splitea nunca maneja el dinero.",
        tagline: "Solicita · Cobra · Repite",
      },
    ],
    pills: {
      contact: "Toca un contacto",
      items: "Toca sus artículos",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "Cóbrales por cualquier app",
      paid: "Ellos eligen cómo pagarte",
    },
    stepGo: (n: number, label: string) => `Ir al paso ${n}: ${label}`,
    play: "Reproducir la demo",
    pause: "Pausar la demo",
    videoLabel: "Asignar artículos: toca un contacto y luego toca los artículos que pidió.",
    endTitle: "Pruébalo en tu próxima cena.",
    endNote: "Descarga gratuita.",
  },
  send: {
    title: "Envía el [[link]].\nCada quien elige.",
    tagline: "Sin app · Sin registro para tus amigos",
    body: "Comparte un solo enlace en vivo por Mensajes, WhatsApp o Mail, con una tarjeta de vista previa de Splitea. Tus amigos lo abren en cualquier navegador, incluso en Android, y tocan lo que pidieron. Todos los que tienen el enlace ven cada elección en tiempo real, y puedes bloquear la edición cuando termines.",
    line: "El teléfono del inicio de esta página muestra esa misma página.",
    tryIt: "Pruébalo",
    connected: "Conectados (3)",
    anyBrowser: "Se abre en cualquier navegador",
    cardAlt: "Una tarjeta de vista previa de un enlace de Splitea en un chat.",
  },
  trips: {
    title: "Un [[viaje]].\nUn resumen.",
    tagline: "Agrupa · Comparte · Cobra",
    body: "Guarda los recibos de un viaje en una carpeta. El Resumen de carpeta suma el total de cada persona en todos los splits y reconoce a la misma persona aunque su número esté guardado de otra forma. Luego, con Exportar carpeta compartes un solo PDF con el total de cada uno.",
    alt: "Una carpeta de viaje con varios recibos.",
  },
  digital: {
    title: "¿Recibo [[digital]]?\nAún más fácil.",
    tagline: "Safari · Compartir · Splitea",
    body: "¿Te llegó el recibo como página web o PDF? Compártelo desde Safari, Archivos o Mail y elige Splitea. Las páginas web se convierten en un PDF con texto real antes de leerse. Si la página pide iniciar sesión, usa la opción PDF de Safari.",
    pills: ["Toca Compartir", "Elige Splitea"],
    alt: "El menú Compartir de iOS con Splitea en la fila de apps.",
  },
  abroad: {
    title: "¿Otra moneda?\nDivide en la [[tuya]].",
    tagline: "Convierte · Traduce · Cobra",
    body: "Convierte un split a tu moneda con el monto del estado de cuenta de tu tarjeta, tu propio tipo de cambio o el del mercado de hoy. Las partes convertidas siguen sumando el total convertido, y tus amigos ven el tipo de cambio en su página. También funcionan las monedas sin centavos, como el yen y el won.",
    translateBefore: "Los nombres de artículos escritos en otro alfabeto vienen con su traducción a tu idioma, como ",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: " (Bibimbap). La app está en 10 idiomas.",
    alt: "La pantalla de conversión de moneda, de pesos a dólares.",
    payTitle: "Tus amigos pagan con la app que ya usan.",
    regions: [
      { title: "Estados Unidos", text: "Venmo, Cash App, PayPal, Revolut y ATH Móvil. Venmo se abre con el monto y una nota ya completados." },
      { title: "Puerto Rico", text: "ATH Móvil, Venmo, Cash App, PayPal y Revolut. Con ATH Móvil, tu amigo escribe el monto." },
      { title: "Reino Unido e Irlanda", text: "Monzo, Revolut y PayPal, con el monto ya completado." },
      { title: "Europa", text: "Revolut y PayPal, con el monto ya completado." },
      { title: "India", text: "Google Pay UPI en rupias, con el monto ya completado." },
    ],
    prev: "Región anterior",
    next: "Región siguiente",
    footnote: "PayPal funciona en la mayoría de los países. ¿No configuraste ninguna app de pagos? Aun así, tus amigos pueden marcar su parte como pagada. Apple Pay, Apple Cash y Zelle no son compatibles.",
  },
  privacy: {
    title: "Tus recibos.\nTu [[iCloud]].",
    tagline: "Sin anuncios · Sin rastreadores · Tu iCloud",
    body: "Tus splits guardados, tus carpetas y tu perfil se sincronizan a través de tu propio iCloud, y los servidores de Splitea no guardan tu biblioteca de recibos. Las fotos de tus contactos se quedan en tu iPhone, y un nombre solo sale de él cuando compartes un split en el que está esa persona. Esto es lo que sí sale.",
    facts: [
      {
        title: "Se lee, no se guarda.",
        text: "Para leer un recibo, la foto va al servidor de Splitea y a un modelo de IA (actualmente Google Gemini). El servicio de escaneo no guarda la imagen. Sí guarda un registro de cada escaneo con tu cuenta, las versiones de la app y de iOS, y el país. Si permites el acceso a la ubicación, también se envía una ubicación aproximada para elegir la tasa de impuesto.",
      },
      {
        title: "Los enlaces caducan a los 30 días.",
        text: "Cuando compartes un split, se envía una copia al servidor de compartición de Splitea: los artículos y los montos, la foto del recibo, los nombres y números de teléfono de las personas del split y tus nombres de usuario de pago. El enlace caduca 30 días después de crearlo.",
      },
      {
        title: "Sin anuncios. Sin rastreadores.",
        text: "La app no tiene anuncios, SDK de rastreo ni paquetes de terceros. Nuestras páginas web solo cuentan las visitas, con Cloudflare Web Analytics y sin cookies.",
      },
      {
        title: "Tu perfil, hasta que lo elimines.",
        text: "Tu nombre, tu foto, tu número de teléfono, tu correo electrónico y tus nombres de usuario de pago se guardan en los servidores de Splitea para que tus amigos puedan encontrarte y pagarte, y la app busca ahí los números de teléfono de tus splits. Al eliminar tu cuenta en Configuración, se cierran los splits que compartiste, se elimina ese perfil y se borran tus recibos de tu iPhone y de iCloud.",
      },
    ],
    link: "Lee la política de privacidad",
  },
  pricing: {
    title: "Empieza con [[3]] escaneos gratis.",
    tagline: "Descarga gratuita · 3 escaneos gratis",
    body: "Splitea es de descarga gratuita y cada cuenta recibe 3 escaneos gratis: 3 en total, no 3 al mes. Después, para agregar un recibo nuevo necesitas Splitea Unlimited, ya sea que lo escanees, lo importes como foto o PDF, lo compartas desde otra app o lo escribas a mano. Dividir, compartir enlaces, editar en vivo, saldar cuentas, usar carpetas, exportar a PDF y convertir monedas no requieren suscripción. Abrir un enlace siempre es gratis para tus amigos.",
    plan: "Splitea Unlimited",
    checks: ["Recibos ilimitados, escaneados, importados o escritos a mano", "Color de acento personalizado"],
    price: (monthly: string, yearly: string) => `${monthly} al mes o ${yearly} al año en EE. UU.`,
    vary: "Los precios varían según el país.",
    fine: "Una lectura que falla no gasta un escaneo, y volver a escanear la misma foto no se cuenta dos veces.",
  },
  faq: {
    title: "Tus preguntas, [[respondidas]].",
    items: [
      {
        q: "¿Mis amigos necesitan Splitea o un iPhone?",
        a: "No. Tu enlace se abre en cualquier navegador, también en teléfonos Android y computadoras, sin app y sin cuenta. La página está en 10 idiomas, y ellos pagan con su propia app de pagos.",
      },
      {
        q: "¿Necesito una cuenta?",
        a: "Sí. Inicias sesión con Apple para escanear y compartir, y Splitea pide acceso a Contactos para que puedas elegir a las personas. Funciona con acceso completo o limitado.",
      },
      {
        q: "¿Qué puedo hacer sin suscribirme?",
        a: "Todo con los recibos que ya tienes. Compartir enlaces, editar en vivo, saldar cuentas, usar carpetas, exportar a PDF y convertir monedas no requieren suscripción, y tampoco los splits que te envían tus amigos. Después de tus 3 escaneos gratis, para agregar un recibo nuevo, ya sea con la cámara, una foto, un PDF, el menú Compartir o a mano, necesitas Splitea Unlimited, que también desbloquea un color de acento personalizado.",
      },
      {
        q: "¿Splitea maneja el dinero?",
        a: "No. Splitea nunca mueve dinero. Abre la app o el enlace de pago de tu amigo: Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo o Google Pay UPI, según tu país. Cada una se abre con el monto ya completado, excepto ATH Móvil, donde tu amigo lo escribe. Apple Pay, Apple Cash y Zelle no son compatibles, pero aun así tus amigos pueden marcar su parte como pagada.",
      },
      {
        q: "¿Y si un recibo se lee mal?",
        a: "Splitea compara su subtotal, impuesto y total con el recibo impreso y te avisa cuando no coinciden. Toca cualquier artículo para cambiar su descripción, precio o impuesto. La cámara también te avisa cuando una foto tiene reflejos, está borrosa, deja fuera parte del recibo, muestra un menú en lugar de la cuenta o incluye varios recibos.",
      },
      {
        q: "¿Funciona fuera de Estados Unidos?",
        a: "Sí. Splitea está en el App Store de muchos países, como el Reino Unido, México, Japón, Alemania, India, Brasil y Corea del Sur. Divide en la moneda del recibo, incluidas las que no tienen centavos, como el yen y el won, maneja recibos con el impuesto ya incluido, como los de Japón y la UE, y puede convertir un split a tu moneda.",
      },
      {
        q: "iOS 27 puede dividir cuentas. ¿Por qué usar Splitea?",
        a: "La función de Apple para dividir cuentas viene integrada y es gratis. Funciona con Apple Cash, que está disponible en los 50 estados de EE. UU., el Distrito de Columbia y Puerto Rico para residentes de EE. UU. de 18 años o más con un iPhone, iPad o Apple Watch. Con Splitea, tus amigos abren tu enlace en cualquier teléfono o computadora y pagan con apps como Venmo, PayPal o ATH Móvil. Además, Splitea funciona en muchos países y para escanear no hace falta Apple Intelligence. Cada amigo elige sus artículos en vivo, cada artículo lleva su impuesto local y los recibos de un viaje se suman en un solo PDF. Splitea te da 3 escaneos gratis y después requiere una suscripción.",
      },
      {
        q: "¿Cuánto duran los enlaces compartidos?",
        a: "Los enlaces compartidos caducan 30 días después de crearlos. Tu propia copia se queda en tu biblioteca.",
      },
      {
        q: "¿En qué iPhone funciona?",
        a: "En cualquier iPhone con iOS 26 o posterior. No hay app para iPad, Mac ni Android, así que tus amigos con otros dispositivos usan el enlace en su navegador.",
      },
    ],
    dataQ: "¿Dónde están mis datos?",
    dataBefore: "Tus recibos guardados, tus carpetas y tu perfil se sincronizan a través de tu propio iCloud. La ",
    dataLink: "sección de privacidad",
    dataAfter: " de arriba explica qué se envía a los servidores de Splitea y por cuánto tiempo.",
  },
  get: {
    pronunciation: "",
    title: "Cada recibo, a [[un toque]].",
    body: "Cada split que guardas se queda en tu biblioteca, sincronizado a través de tu propio iCloud. Abre uno para ver quién ya pagó.",
    small: "Descarga gratuita, con 3 escaneos gratis. Solo para iPhone, con iOS 26 o posterior.",
    qrCaption: "¿Estás en una computadora? Escanea con la cámara de tu iPhone.",
    tagline: "Splitea · Tu cuenta, resuelta",
    gridAlt: "La biblioteca Todos los splits.",
    listAlt: "La biblioteca Todos los splits en forma de lista.",
  },
  footer: {
    origin: "Splitea · Hecho en Puerto Rico",
    languages: "Idioma",
    privacy: "Privacidad",
    terms: "Términos",
    appStore: "App Store",
    legal: [
      "Apple, el logotipo de Apple, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash y Apple Intelligence son marcas comerciales de Apple Inc., registradas en EE. UU. y en otros países y regiones. App Store es una marca de servicio de Apple Inc.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp y Zelle son marcas comerciales de sus respectivos propietarios. Splitea no está afiliada a ellos.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "Descarga Splitea en el App Store",
};

export default es;
