import type { Copy } from "./en";

const fr: Copy = {
  meta: {
    title: "Splitea pour iPhone : partager l'addition entre amis",
    description: "Photographiez le reçu, indiquez qui a pris quoi, envoyez un lien. Vos amis choisissent leurs articles sans app, et le compte est bon au centime près.",
    ogTitle: "Splitea : partagez l'addition au centime près",
    ogDescription: "Photographiez le reçu, indiquez qui a pris quoi, envoyez un lien. Vos amis choisissent leurs articles dans leur navigateur. Pour iPhone.",
    ogImageAlt: "Partagez l'addition au centime près. L'écran Attribuer les articles de Splitea sur un iPhone, avec les légendes « 1 Touchez un contact » et « 2 Touchez ses articles ».",
    ogTagline: "Pour iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "Comment ça marche" },
      { id: "trips", label: "Voyages" },
      { id: "abroad", label: "À l'étranger" },
      { id: "privacy", label: "Confidentialité" },
      { id: "pricing", label: "Tarifs" },
    ],
    cta: "Obtenir Splitea",
    dismiss: "Fermer",
    qrLine: "Scannez avec l'appareil photo de votre iPhone pour obtenir Splitea.",
    qrLink: "Ouvrir la page de l'App Store",
  },
  hero: {
    titleTop: "Partagez l'addition",
    titleBottom: "au [[centime]] près.",
    tagline: "Chaque centime à sa place",
    body: "Photographiez le reçu, indiquez qui a pris quoi et envoyez le lien. Vos amis choisissent leurs articles dans n'importe quel navigateur et vous remboursent. Ils n'ont pas besoin de l'app.",
    noteTop: "Téléchargement gratuit.",
    noteBottom: "Pour iPhone sous iOS 26 ou version ultérieure.",
    android: "Sur Android ? Les liens Splitea s'ouvrent directement dans votre navigateur. L'app est réservée à l'iPhone.",
    pills: ["Touchez un contact", "Touchez ses articles"],
    tryIt: "Essayez en direct",
    done: "Terminé",
    demoLabel: "Démo en direct · la page qu'ouvrent vos amis",
    demoNote: "Ce téléphone est interactif. C'est exactement la page qu'ouvrent vos amis.",
    qrCaption: "Sur un ordinateur ? Scannez avec l'appareil photo de votre iPhone.",
  },
  how: {
    title: "Scannez, touchez, envoyez.\nSoyez [[remboursé]].",
    tagline: "Scan · Attribution · Taxes · Règlement",
    body: "Photographiez l'addition, indiquez qui a pris quoi, et Splitea calcule la taxe, le pourboire et chaque centime. Ensuite, vos amis vous remboursent à leur façon.",
    steps: [
      {
        rail: "Scan",
        title: "Scannez le [[reçu]].",
        body: "Splitea lit les articles et les prix pour vous. Si un reflet ou un flou cache un prix, l'appareil photo vous le signale.",
        tagline: "Appareil photo · Photos · PDF",
      },
      {
        rail: "Attribution",
        title: "Touchez un contact.\nTouchez ses [[articles]].",
        body: "Les plats partagés sont répartis entre ceux qui en ont pris, et d'un seul geste, un article est attribué à tout le monde.",
        tagline: "Qui a pris quoi",
      },
      {
        rail: "Taxes",
        title: "Taxes [[locales]], automatiques.",
        body: "Chaque article reçoit son propre taux, vérifié par rapport à la taxe imprimée. Ici : 7 % sur le mofongo, 11,5 % sur l'Old Fashioned.",
        tagline: "Fini les calculs de tête",
      },
      {
        rail: "Règlement",
        title: "Tout réglé, [[simplement]].",
        body: "Vos amis touchent Payer pour ouvrir Venmo, PayPal ou Cash App avec leur montant. Splitea ne touche jamais à l'argent.",
        tagline: "Réclamer · Récupérer · Récidiver",
      },
    ],
    pills: {
      contact: "Touchez un contact",
      items: "Touchez ses articles",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "Demandez par message",
      paid: "Soyez payé via leur app",
    },
    stepGo: (n: number, label: string) => `Aller à l'étape ${n} : ${label}`,
    play: "Lire la démo",
    pause: "Mettre la démo en pause",
    videoLabel: "Attribution des articles : touchez un contact, puis touchez ses articles.",
    endTitle: "Essayez Splitea à votre prochain dîner.",
    endNote: "Téléchargement gratuit.",
  },
  send: {
    title: "Passez le [[lien]].\nIls cochent.",
    tagline: "Sans app · Sans compte pour vos amis",
    body: "Partagez un seul lien en direct dans Messages, WhatsApp ou Mail, avec une carte d'aperçu Splitea. Vos amis l'ouvrent dans n'importe quel navigateur, Android compris, et touchent ce qu'ils ont pris. Toutes les personnes qui ont le lien voient chaque choix en temps réel, et vous pouvez verrouiller la modification quand vous avez terminé.",
    line: "Le téléphone en haut de cette page affiche justement la page de vos amis.",
    tryIt: "Essayez",
    connected: "Connectés (3)",
    anyBrowser: "S'ouvre dans tout navigateur",
    cardAlt: "Une carte d'aperçu de lien Splitea dans une conversation.",
  },
  trips: {
    title: "Un seul [[voyage]].\nUn seul résumé.",
    tagline: "Regrouper · Partager · Encaisser",
    body: "Rangez les reçus d'un voyage dans un dossier. Le Résumé du dossier cumule le total de chaque personne sur toutes les additions, et reconnaît la même personne même si son numéro est enregistré différemment. Avec Exporter le dossier, partagez ensuite un seul PDF avec le total de chacun.",
    alt: "Un dossier de voyage contenant plusieurs reçus.",
  },
  digital: {
    title: "Reçu [[numérique]] ?\nEncore mieux.",
    tagline: "Safari · Partager · Splitea",
    body: "Votre reçu est une page web ou un PDF ? Partagez-le depuis Safari, Fichiers ou Mail et choisissez Splitea. Les pages web sont converties en PDF avec du vrai texte avant d'être lues. Si la page demande une connexion, utilisez l'option PDF de Safari.",
    pills: ["Touchez Partager", "Choisissez Splitea"],
    alt: "La feuille de partage d'iOS avec Splitea dans la rangée d'apps.",
  },
  abroad: {
    title: "Addition à l'étranger ?\nPartagez dans votre [[devise]].",
    tagline: "Convertir · Traduire · Régler",
    body: "Convertissez une addition dans votre devise avec le montant figurant sur votre relevé de carte, votre propre taux ou le taux du marché du jour. La somme des parts converties correspond toujours au total converti, et vos amis voient le taux sur leur page. Les devises sans centimes, comme le yen et le won, fonctionnent aussi.",
    translateBefore: "Les noms d'articles écrits dans un autre alphabet sont accompagnés d'une traduction dans votre langue, comme ",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: " (Bibimbap). L'app parle 10 langues.",
    alt: "La feuille de conversion de devise, des pesos aux dollars.",
    payTitle: "Vos amis paient avec l'app qu'ils utilisent déjà.",
    regions: [
      { title: "États-Unis", text: "Venmo, Cash App, PayPal, Revolut et ATH Móvil. Venmo s'ouvre avec le montant et une note préremplis." },
      { title: "Porto Rico", text: "ATH Móvil, Venmo, Cash App, PayPal et Revolut. Avec ATH Móvil, votre ami saisit le montant." },
      { title: "Royaume-Uni et Irlande", text: "Monzo, Revolut et PayPal, avec le montant prérempli." },
      { title: "Europe", text: "Revolut et PayPal, avec le montant prérempli." },
      { title: "Inde", text: "Google Pay UPI en roupies, avec le montant prérempli." },
    ],
    prev: "Région précédente",
    next: "Région suivante",
    footnote: "PayPal fonctionne dans la plupart des pays. Aucune app de paiement configurée ? Vos amis peuvent quand même marquer leur part comme payée. Apple Pay, Apple Cash et Zelle ne sont pas pris en charge.",
  },
  privacy: {
    title: "Vos reçus.\nVotre [[iCloud]].",
    tagline: "Sans pub · Sans pistage · Votre iCloud",
    body: "Les additions enregistrées, les dossiers et votre profil se synchronisent via votre propre iCloud, et les serveurs de Splitea ne conservent pas votre bibliothèque de reçus. Les photos des contacts restent sur votre iPhone, et un nom n'en sort que lorsque vous partagez une addition où figure cette personne. Voici ce qui en sort.",
    facts: [
      {
        title: "Lu, pas conservé.",
        text: "Pour lire un reçu, la photo est envoyée au serveur de Splitea et à un modèle d'IA (actuellement Google Gemini). Le service de scan ne conserve pas l'image. Il garde en revanche un enregistrement de chaque scan avec votre compte, les versions de l'app et d'iOS, et le pays. Si vous autorisez la localisation, une position approximative est aussi envoyée pour aider à choisir le taux de taxe.",
      },
      {
        title: "Les liens expirent au bout de 30 jours.",
        text: "Quand vous partagez une addition, une copie est envoyée au serveur de partage de Splitea : les articles et les montants, la photo du reçu, les noms et numéros de téléphone des personnes concernées, et vos noms d'utilisateur de paiement. Le lien expire 30 jours après sa création.",
      },
      {
        title: "Pas de pub. Pas de pistage.",
        text: "L'app ne contient ni publicité, ni SDK de pistage, ni bibliothèque tierce. Nos pages web se contentent de compter les visites, avec Cloudflare Web Analytics, sans cookies.",
      },
      {
        title: "Votre profil, jusqu'à ce que vous le supprimiez.",
        text: "Votre nom, votre photo, votre numéro de téléphone, votre adresse e-mail et vos noms d'utilisateur de paiement sont conservés sur les serveurs de Splitea pour que vos amis puissent vous trouver et vous payer, et l'app compare à ces profils les numéros de téléphone de vos additions. Supprimer votre compte dans Réglages met fin à vos partages, efface ce profil et supprime vos reçus de votre iPhone et d'iCloud.",
      },
    ],
    link: "Lire la politique de confidentialité",
  },
  pricing: {
    title: "Commencez avec [[3]] scans gratuits.",
    tagline: "Téléchargement gratuit · 3 scans gratuits",
    body: "Splitea est gratuit à télécharger, et chaque compte dispose de 3 scans gratuits : 3 au total, pas 3 par mois. Ensuite, ajouter un nouveau reçu nécessite Splitea Unlimited, que vous le scanniez, importiez une photo ou un PDF, l'envoyiez depuis une autre app ou le saisissiez à la main. Diviser l'addition, partager des liens, modifier en direct, régler les comptes, utiliser les dossiers, exporter en PDF et convertir les devises ne demandent aucun abonnement. Ouvrir un lien est toujours gratuit pour vos amis.",
    plan: "Splitea Unlimited",
    checks: ["Reçus illimités, scannés, importés ou saisis", "Couleur d'accentuation personnalisée"],
    price: (monthly: string, yearly: string) => `${monthly} par mois ou ${yearly} par an aux États-Unis.`,
    vary: "Les prix varient selon les pays.",
    fine: "Une lecture qui échoue ne consomme pas de scan, et scanner à nouveau la même photo n'est pas compté deux fois.",
  },
  faq: {
    title: "Vos questions, nos [[réponses]].",
    items: [
      {
        q: "Mes amis ont-ils besoin de Splitea ou d'un iPhone ?",
        a: "Non. Votre lien s'ouvre dans n'importe quel navigateur, y compris sur les téléphones Android et les ordinateurs portables, sans app ni compte. La page existe en 10 langues, et ils paient avec leur propre app de paiement.",
      },
      {
        q: "Ai-je besoin d'un compte ?",
        a: "Oui. Vous vous connectez avec Apple pour scanner et partager, et Splitea demande l'accès à vos Contacts pour que vous puissiez choisir les participants. L'accès complet comme l'accès limité fonctionnent.",
      },
      {
        q: "Que puis-je faire sans abonnement ?",
        a: "Tout, avec les reçus que vous avez déjà. Partager des liens, modifier en direct, régler les comptes, utiliser les dossiers, exporter en PDF et convertir les devises ne demandent aucun abonnement, pas plus que les additions que vos amis vous envoient. Après vos 3 scans gratuits, ajouter un nouveau reçu, par l'appareil photo, une photo, un PDF, la feuille de partage ou à la main, nécessite Splitea Unlimited, qui débloque aussi une couleur d'accentuation personnalisée.",
      },
      {
        q: "Splitea gère-t-il l'argent ?",
        a: "Non. Splitea ne déplace jamais d'argent. Il ouvre l'app ou le lien de paiement de votre ami : Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo ou Google Pay UPI, selon votre pays. Chacun s'ouvre avec le montant prérempli, sauf ATH Móvil, où votre ami le saisit. Apple Pay, Apple Cash et Zelle ne sont pas pris en charge, mais vos amis peuvent quand même marquer leur part comme payée.",
      },
      {
        q: "Et si un reçu est mal lu ?",
        a: "Splitea compare le sous-total, la taxe et le total qu'il calcule à ceux imprimés sur le reçu, et vous prévient s'ils ne correspondent pas. Touchez un article pour modifier sa description, son prix ou sa taxe. L'appareil photo vous signale aussi quand une photo a des reflets ou est floue, coupe le reçu, montre un menu au lieu de l'addition ou contient plusieurs reçus.",
      },
      {
        q: "Est-ce que ça marche en dehors des États-Unis ?",
        a: "Oui. Splitea est disponible sur l'App Store dans de nombreux pays, dont le Royaume-Uni, le Mexique, le Japon, l'Allemagne, l'Inde, le Brésil et la Corée du Sud. Il partage l'addition dans la devise du reçu, y compris celles sans centimes comme le yen et le won, gère les reçus où la taxe est déjà incluse (TTC), comme au Japon et dans l'UE, et peut convertir une addition dans votre devise.",
      },
      {
        q: "iOS 27 sait partager l'addition. Pourquoi utiliser Splitea ?",
        a: "La fonction de partage d'addition d'Apple est intégrée et gratuite. Elle repose sur Apple Cash, qui fonctionne dans les 50 États américains, le district de Columbia et Porto Rico pour les résidents américains de 18 ans ou plus, avec un iPhone, un iPad ou une Apple Watch. Avec Splitea, vos amis ouvrent votre lien sur n'importe quel téléphone ou ordinateur et paient avec des apps comme Venmo, PayPal ou ATH Móvil. Splitea fonctionne dans de nombreux pays, et le scan ne nécessite pas Apple Intelligence. Chaque ami choisit ses propres articles en direct, chaque article reçoit sa taxe locale, et les reçus d'un voyage s'additionnent dans un seul PDF. Splitea vous offre 3 scans gratuits, puis nécessite un abonnement.",
      },
      {
        q: "Combien de temps durent les liens de partage ?",
        a: "Les liens de partage expirent 30 jours après leur création. Votre propre copie reste dans votre bibliothèque.",
      },
      {
        q: "Sur quels iPhone Splitea fonctionne-t-il ?",
        a: "Sur tout iPhone sous iOS 26 ou version ultérieure. Il n'existe pas d'app pour iPad, Mac ou Android : vos amis sur d'autres appareils utilisent le lien dans leur navigateur.",
      },
    ],
    dataQ: "Où sont mes données ?",
    dataBefore: "Les reçus enregistrés, les dossiers et votre profil se synchronisent via votre propre iCloud. La ",
    dataLink: "rubrique Confidentialité",
    dataAfter: " plus haut indique ce qui est envoyé aux serveurs de Splitea et pour combien de temps.",
  },
  get: {
    pronunciation: "/ spli·TÉ·a /",
    title: "Chaque reçu, [[sous la main]].",
    body: "Chaque addition que vous enregistrez reste dans votre bibliothèque, synchronisée via votre propre iCloud. Ouvrez-en une pour voir qui a payé.",
    small: "Téléchargement gratuit, avec 3 scans gratuits. iPhone uniquement, iOS 26 ou version ultérieure.",
    qrCaption: "Sur un ordinateur ? Scannez avec l'appareil photo de votre iPhone.",
    tagline: "Splitea · Votre addition, réglée",
    gridAlt: "La bibliothèque Tous les partages.",
    listAlt: "La bibliothèque Tous les partages, en liste.",
  },
  footer: {
    origin: "Splitea · Conçu à Porto Rico",
    languages: "Langue",
    privacy: "Confidentialité",
    terms: "Conditions",
    appStore: "App Store",
    legal: [
      "Apple, le logo Apple, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash et Apple Intelligence sont des marques d'Apple Inc., déposées aux États-Unis et dans d'autres pays et régions. App Store est une marque de service d'Apple Inc.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp et Zelle sont des marques de leurs propriétaires respectifs. Splitea n'est affilié à aucun d'entre eux.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "Télécharger Splitea dans l'App Store",
};

export default fr;
