import type { Copy } from "./en";

const it: Copy = {
  meta: {
    title: "Splitea per iPhone: dividi il conto tra amici, al centesimo",
    description: "Fotografa lo scontrino, tocca chi ha preso cosa e manda un link. Gli amici scelgono i loro articoli dal browser, senza app, e i conti tornano al centesimo.",
    ogTitle: "Splitea: dividi il conto fino all'ultimo centesimo",
    ogDescription: "Fotografa lo scontrino, tocca chi ha preso cosa, manda un link. Gli amici scelgono i loro articoli in qualsiasi browser. Per iPhone.",
    ogImageAlt: "Dividi il conto fino all'ultimo centesimo. La schermata Assegna articoli di Splitea su un iPhone con le etichette 1 Tocca un contatto e 2 Tocca i suoi articoli.",
    ogTagline: "Per iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "Come funziona" },
      { id: "trips", label: "Viaggi" },
      { id: "abroad", label: "All'estero" },
      { id: "privacy", label: "Privacy" },
      { id: "pricing", label: "Prezzi" },
    ],
    cta: "Ottieni Splitea",
    dismiss: "Chiudi",
    qrLine: "Inquadra con la fotocamera dell'iPhone per scaricare Splitea.",
    qrLink: "Apri la pagina dell'App Store",
  },
  hero: {
    titleTop: "Dividi il conto",
    titleBottom: "al [[centesimo]].",
    tagline: "Ogni centesimo al suo posto",
    body: "Fotografa lo scontrino, tocca chi ha preso cosa e manda il link. Gli amici scelgono i loro articoli in qualsiasi browser e ti rimborsano. A loro l'app non serve.",
    noteTop: "Download gratuito.",
    noteBottom: "Per iPhone con iOS 26 o versioni successive.",
    android: "Hai Android? I link di Splitea si aprono direttamente nel browser. L'app è per iPhone.",
    pills: ["Tocca un contatto", "Tocca i suoi articoli"],
    tryIt: "Prova la demo",
    done: "Fatto",
    demoLabel: "Demo live · la pagina che aprono i tuoi amici",
    demoNote: "Quel telefono funziona davvero. È proprio la pagina che aprono i tuoi amici.",
    qrCaption: "Sei al computer? Inquadra con la fotocamera dell'iPhone.",
  },
  how: {
    title: "Scatta, tocca, invia.\nFatti [[rimborsare]].",
    tagline: "Scansiona · Assegna · Tasse · Salda",
    body: "Fotografa il conto, tocca chi ha preso cosa e Splitea calcola tasse, mancia e ogni centesimo. Poi gli amici ti rimborsano come preferiscono.",
    steps: [
      {
        rail: "Scansiona",
        title: "Fotografa lo [[scontrino]].",
        body: "Splitea legge articoli e prezzi per te. Se per un riflesso o una foto mossa un prezzo non si legge, la fotocamera te lo dice.",
        tagline: "Fotocamera · Foto · PDF",
      },
      {
        rail: "Assegna",
        title: "Tocca un contatto.\nTocca i suoi [[articoli]].",
        body: "I piatti condivisi si dividono tra chi li ha presi, e con un tocco un articolo va a tutti.",
        tagline: "Chi ha preso cosa",
      },
      {
        rail: "Tasse",
        title: "Tasse [[locali]], automatiche.",
        body: "Ogni articolo ha la sua aliquota, confrontata con le tasse stampate sullo scontrino. Qui: 7% sul mofongo, 11,5% sull'Old Fashioned.",
        tagline: "Zero calcoli a mano",
      },
      {
        rail: "Salda",
        title: "Tutto saldato, [[semplice]].",
        body: "Gli amici toccano Paga per aprire Venmo, PayPal o Cash App con l'importo che devono. Splitea non tocca mai i soldi.",
        tagline: "Richiedi · Ricevi · Ripeti",
      },
    ],
    pills: {
      contact: "Tocca un contatto",
      items: "Tocca i suoi articoli",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "Richiedi da qualsiasi app",
      paid: "Ti pagano come preferiscono",
    },
    stepGo: (n: number, label: string) => `Vai al passaggio ${n}: ${label}`,
    play: "Avvia la demo",
    pause: "Metti in pausa la demo",
    videoLabel: "Assegnare gli articoli: tocca un contatto, poi tocca gli articoli che ha preso.",
    endTitle: "Provala alla tua prossima cena.",
    endNote: "Download gratuito.",
  },
  send: {
    title: "Manda il [[link]].\nScelgono loro.",
    tagline: "Niente app · Niente account per gli amici",
    body: "Condividi un unico link live su Messaggi, WhatsApp o Mail, con una scheda di anteprima di Splitea. Gli amici lo aprono in qualsiasi browser, anche su Android, e toccano ciò che hanno preso. Chiunque abbia il link vede ogni scelta in tempo reale, e quando hai finito puoi bloccare la modifica.",
    line: "Il telefono in cima a questa pagina è proprio quella pagina.",
    tryIt: "Provala",
    connected: "Connessi (3)",
    anyBrowser: "Si apre in qualsiasi browser",
    cardAlt: "La scheda di anteprima di un link Splitea in una chat.",
  },
  trips: {
    title: "Un [[viaggio]].\nUn solo conto.",
    tagline: "Raggruppa · Condividi · Incassa",
    body: "Metti gli scontrini di un viaggio in una cartella. Il Riepilogo cartella somma il totale di ogni persona su tutte le divisioni e riconosce la stessa persona anche quando il suo numero è salvato in modo diverso. Poi, con Esporta cartella, condividi un solo PDF con il totale di ciascuno.",
    alt: "Una cartella di viaggio con diversi scontrini.",
  },
  digital: {
    title: "Scontrino [[digitale]]?\nAncora più facile.",
    tagline: "Safari · Condividi · Splitea",
    body: "Hai lo scontrino come pagina web o PDF? Condividilo da Safari, File o Mail e scegli Splitea. Le pagine web diventano un PDF con testo vero prima di essere lette. Se la pagina richiede l'accesso, usa l'opzione PDF di Safari.",
    pills: ["Tocca Condividi", "Scegli Splitea"],
    alt: "Il menu Condividi di iOS con Splitea nella riga delle app.",
  },
  abroad: {
    title: "Valuta estera?\nDividi nella [[tua]].",
    tagline: "Converti · Traduci · Salda",
    body: "Converti una divisione nella tua valuta usando l'importo sull'estratto conto della carta, un cambio a tua scelta o il cambio di mercato di oggi. La somma delle quote convertite corrisponde comunque al totale convertito, e gli amici vedono il cambio applicato nella loro pagina. Funzionano anche le valute senza centesimi, come lo yen e il won.",
    translateBefore: "I nomi degli articoli scritti in un altro alfabeto sono accompagnati dalla traduzione nella tua lingua, come ",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: " (Bibimbap). L'app parla 10 lingue.",
    alt: "Il pannello di conversione della valuta, da pesos a dollari.",
    payTitle: "Gli amici pagano con l'app che usano già.",
    regions: [
      { title: "Stati Uniti", text: "Venmo, Cash App, PayPal, Revolut e ATH Móvil. Venmo si apre con l'importo e una nota già compilati." },
      { title: "Porto Rico", text: "ATH Móvil, Venmo, Cash App, PayPal e Revolut. Con ATH Móvil, l'importo lo digita il tuo amico." },
      { title: "Regno Unito e Irlanda", text: "Monzo, Revolut e PayPal, con l'importo già compilato." },
      { title: "Europa", text: "Revolut e PayPal, con l'importo già compilato." },
      { title: "India", text: "Google Pay UPI in rupie, con l'importo già compilato." },
    ],
    prev: "Regione precedente",
    next: "Regione successiva",
    footnote: "PayPal funziona nella maggior parte dei paesi. Nessuna app di pagamento configurata? Gli amici possono comunque segnare la loro parte come pagata. Apple Pay, Apple Cash e Zelle non sono supportati.",
  },
  privacy: {
    title: "I tuoi scontrini.\nIl tuo [[iCloud]].",
    tagline: "Niente pubblicità · Niente tracciamento · Il tuo iCloud",
    body: "Le divisioni salvate, le cartelle e il tuo profilo si sincronizzano tramite il tuo iCloud, e i server di Splitea non conservano la tua libreria di scontrini. Le foto dei contatti restano sul tuo iPhone, e un nome ne esce solo quando condividi una divisione in cui c'è quella persona. Ecco invece cosa ne esce.",
    facts: [
      {
        title: "Letto, non conservato.",
        text: "Per leggere uno scontrino, la foto va al server di Splitea e a un modello di IA (attualmente Google Gemini). Il servizio di scansione non conserva l'immagine, ma tiene un registro di ogni scansione con il tuo account, le versioni dell'app e di iOS e il paese. Se consenti l'accesso alla posizione, viene inviata anche una posizione approssimativa per scegliere l'aliquota.",
      },
      {
        title: "I link scadono dopo 30 giorni.",
        text: "Quando condividi una divisione, una copia va al server di condivisione di Splitea: gli articoli e gli importi, la foto dello scontrino, i nomi e i numeri di telefono delle persone coinvolte e i tuoi nomi utente di pagamento. Il link scade 30 giorni dopo la condivisione.",
      },
      {
        title: "Niente pubblicità. Niente tracciamento.",
        text: "L'app non ha pubblicità, né SDK di tracciamento, né pacchetti di terze parti. Le nostre pagine web contano solo le visite, con Cloudflare Web Analytics e senza cookie.",
      },
      {
        title: "Il tuo profilo, finché non lo elimini.",
        text: "Il tuo nome, la foto, il numero di telefono, l'email e i nomi utente di pagamento sono conservati sui server di Splitea così gli amici possono trovarti e pagarti, e l'app confronta con questi profili i numeri di telefono delle tue divisioni. Eliminando il tuo account in Impostazioni chiudi le tue condivisioni, rimuovi quel profilo e cancelli i tuoi scontrini dall'iPhone e da iCloud.",
      },
    ],
    link: "Leggi l'informativa sulla privacy",
  },
  pricing: {
    title: "Inizia con [[3]] scansioni gratuite.",
    tagline: "Download gratuito · 3 scansioni gratuite",
    body: "Splitea si scarica gratis, e ogni account ha 3 scansioni gratuite: 3 in tutto, non 3 al mese. Una volta esaurite, per aggiungere un nuovo scontrino serve Splitea Unlimited, sia che tu lo scansioni, importi una foto o un PDF, lo condivida in Splitea o lo inserisca a mano. Per dividere, condividere link, modificare in tempo reale, saldare i conti, usare le cartelle, esportare PDF e convertire valute non serve l'abbonamento. Per i tuoi amici aprire un link è sempre gratis.",
    plan: "Splitea Unlimited",
    checks: ["Scontrini illimitati, scansionati, importati o inseriti a mano", "Colore accento personalizzato"],
    price: (monthly: string, yearly: string) => `${monthly} al mese o ${yearly} all'anno negli Stati Uniti.`,
    vary: "I prezzi variano in base al paese.",
    fine: "Una lettura non riuscita non consuma una scansione, e scansionare di nuovo la stessa foto non ne consuma un'altra.",
  },
  faq: {
    title: "Domande e [[risposte]].",
    items: [
      {
        q: "Ai miei amici servono Splitea o un iPhone?",
        a: "No. Il tuo link si apre in qualsiasi browser, anche su telefoni Android e computer portatili, senza app e senza account. La pagina è disponibile in 10 lingue, e i tuoi amici pagano con la propria app di pagamento.",
      },
      {
        q: "Mi serve un account?",
        a: "Sì. Accedi con Apple per scansionare e condividere, e Splitea chiede l'accesso ai Contatti così puoi scegliere le persone. Va bene sia l'accesso completo sia quello limitato.",
      },
      {
        q: "Cosa posso fare senza abbonamento?",
        a: "Tutto, con gli scontrini che hai già. Link di condivisione, modifica in tempo reale, saldo dei conti, cartelle, esportazione PDF e conversione di valuta non richiedono l'abbonamento, e nemmeno le divisioni che ti mandano gli amici. Dopo le 3 scansioni gratuite, per aggiungere un nuovo scontrino, con la fotocamera, da foto, da PDF, dal menu Condividi o a mano, serve Splitea Unlimited, che sblocca anche un colore accento personalizzato.",
      },
      {
        q: "Splitea gestisce i soldi?",
        a: "No. Splitea non muove mai denaro. Apre l'app o il link di pagamento del tuo amico: Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo o Google Pay UPI, a seconda del tuo paese. Ognuno si apre con l'importo già compilato, tranne ATH Móvil, dove lo digita il tuo amico. Apple Pay, Apple Cash e Zelle non sono supportati, ma gli amici possono comunque segnare la loro parte come pagata.",
      },
      {
        q: "E se uno scontrino viene letto male?",
        a: "Splitea confronta subtotale, tasse e totale con lo scontrino stampato e ti avvisa quando non corrispondono. Tocca un articolo per modificarne descrizione, prezzo o tasse. La fotocamera ti segnala anche quando una foto ha riflessi o è mossa, taglia fuori parte dello scontrino, inquadra un menù invece del conto o contiene più scontrini.",
      },
      {
        q: "Funziona fuori dagli Stati Uniti?",
        a: "Sì. Splitea è sull'App Store in molti paesi, tra cui Regno Unito, Messico, Giappone, Germania, India, Brasile e Corea. Divide nella valuta dello scontrino, anche in quelle senza centesimi come lo yen e il won, gestisce gli scontrini con le tasse già incluse, come quelli in Giappone e nell'UE, e può convertire una divisione nella tua valuta.",
      },
      {
        q: "iOS 27 sa dividere i conti. Perché usare Splitea?",
        a: "La funzione di Apple per dividere il conto è integrata e gratuita. Si basa su Apple Cash, che funziona nei 50 stati degli Stati Uniti, nel Distretto di Columbia e a Porto Rico per i residenti negli Stati Uniti dai 18 anni in su con un iPhone, un iPad o un Apple Watch. Con Splitea, gli amici aprono il tuo link su qualsiasi telefono o computer e pagano con app come Venmo, PayPal o ATH Móvil. Splitea funziona in molti paesi e la scansione non richiede Apple Intelligence. Ogni amico sceglie i propri articoli in tempo reale, ogni articolo ha la sua aliquota locale e gli scontrini di un viaggio si sommano in un unico PDF. Splitea ti dà 3 scansioni gratuite, poi richiede un abbonamento.",
      },
      {
        q: "Quanto durano i link di condivisione?",
        a: "I link di condivisione scadono 30 giorni dopo la loro creazione. La tua copia resta nella tua libreria.",
      },
      {
        q: "Su quali iPhone funziona?",
        a: "Su qualsiasi iPhone con iOS 26 o versioni successive. Non esiste un'app per iPad, Mac o Android, quindi gli amici su altri dispositivi usano il link nel browser.",
      },
    ],
    dataQ: "Dove sono i miei dati?",
    dataBefore: "Gli scontrini salvati, le cartelle e il tuo profilo si sincronizzano tramite il tuo iCloud. La ",
    dataLink: "sezione sulla privacy",
    dataAfter: " qui sopra elenca cosa va ai server di Splitea e per quanto tempo.",
  },
  get: {
    pronunciation: "",
    title: "Ogni scontrino, a [[un tocco]].",
    body: "Ogni divisione che salvi resta nella tua libreria, sincronizzata tramite il tuo iCloud. Aprine una per vedere chi ha pagato.",
    small: "Download gratuito, con 3 scansioni gratuite. Solo iPhone, iOS 26 o versioni successive.",
    qrCaption: "Sei al computer? Inquadra con la fotocamera dell'iPhone.",
    tagline: "Splitea · Conto sistemato",
    gridAlt: "La libreria Tutte le divisioni.",
    listAlt: "La libreria Tutte le divisioni come elenco.",
  },
  footer: {
    origin: "Splitea · Creata a Porto Rico",
    languages: "Lingua",
    privacy: "Privacy",
    terms: "Termini",
    appStore: "App Store",
    legal: [
      "Apple, il logo Apple, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash e Apple Intelligence sono marchi di Apple Inc., registrati negli Stati Uniti e in altri paesi e aree geografiche. App Store è un marchio di servizio di Apple Inc.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp e Zelle sono marchi dei rispettivi proprietari. Splitea non è affiliata a nessuno di loro.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "Scarica Splitea su App Store",
};

export default it;
