import type { Copy } from "./en";

const ko: Copy = {
  meta: {
    title: "iPhone용 Splitea: 영수증 찍고 친구와 1원까지 정확하게 더치페이",
    description: "친구와 더치페이할 땐 영수증을 찍고 누가 뭘 먹었는지 탭한 뒤 링크 하나만 보내세요. 친구는 앱 없이 어떤 브라우저에서든 자기 항목을 고르고, 각자의 몫을 더하면 합계와 1원까지 딱 맞아요.",
    ogTitle: "Splitea: 1원까지 딱 맞는 더치페이",
    ogDescription: "영수증을 찍고, 누가 뭘 먹었는지 탭하고, 링크를 보내세요. 친구는 어떤 브라우저에서든 자기 항목을 골라요. iPhone용.",
    ogImageAlt: "더치페이, 1원까지 딱 맞게. iPhone에 띄운 Splitea의 항목 배정 화면과 '1 연락처를 탭', '2 항목을 탭' 안내.",
    ogTagline: "iPhone용 · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "사용 방법" },
      { id: "trips", label: "여행" },
      { id: "abroad", label: "해외" },
      { id: "privacy", label: "개인정보" },
      { id: "pricing", label: "가격" },
    ],
    cta: "Splitea 받기",
    dismiss: "닫기",
    qrLine: "iPhone 카메라로 스캔해 Splitea를 받으세요.",
    qrLink: "App Store 페이지 열기",
  },
  hero: {
    titleTop: "더치페이,",
    titleBottom: "[[1원]]까지 딱 맞게.",
    tagline: "한 푼도 빠짐없이",
    body: "영수증을 찍고, 누가 뭘 먹었는지 탭한 뒤 링크를 보내세요. 친구는 어떤 브라우저에서든 자기 항목을 고르고 돈을 갚아요. 앱을 설치할 필요도 없어요.",
    noteTop: "다운로드는 무료예요.",
    noteBottom: "iOS 26 이상의 iPhone에서 쓸 수 있어요.",
    android: "Android를 쓰시나요? Splitea 링크는 브라우저에서 바로 열려요. 앱은 iPhone용이에요.",
    pills: ["연락처를 탭", "항목을 탭"],
    tryIt: "라이브 데모 체험",
    done: "완료",
    demoLabel: "라이브 데모 · 친구가 여는 페이지",
    demoNote: "이 화면은 실제로 작동해요. 친구가 여는 바로 그 페이지예요.",
    qrCaption: "컴퓨터로 보고 계신가요? iPhone 카메라로 스캔하세요.",
  },
  how: {
    title: "찍고, 탭하고, 보내면\n돈이 [[돌아와요]].",
    tagline: "스캔 · 배정 · 세금 · 정산",
    body: "영수증을 찍고 누가 뭘 먹었는지 탭하면, Splitea가 세금과 팁, 마지막 1원까지 계산해요. 그다음 친구들이 각자 편한 방법으로 돈을 갚아요.",
    steps: [
      {
        rail: "스캔",
        title: "[[영수증]]을 찍어요.",
        body: "Splitea가 항목과 가격을 대신 읽어 줘요. 빛 반사나 흔들림 때문에 가격이 가려지면 카메라가 알려 줘요.",
        tagline: "카메라 · 사진 · PDF",
      },
      {
        rail: "배정",
        title: "연락처를 탭하고\n[[항목]]을 탭해요.",
        body: "같이 먹은 메뉴는 먹은 사람끼리 나누고, 한 번만 탭하면 항목을 모두에게 배정할 수 있어요.",
        tagline: "누가 뭘 먹었는지",
      },
      {
        rail: "세금",
        title: "[[현지]] 세율, 자동 적용.",
        body: "항목마다 따로 세율이 적용되고, 영수증에 인쇄된 세금과 대조해 확인해요. 이 영수증에서는 Mofongo에 7%, Old Fashioned에 11.5%가 붙었어요.",
        tagline: "암산은 이제 그만",
      },
      {
        rail: "정산",
        title: "정산은, [[간단하게]].",
        body: "친구가 '결제'를 탭하면 자기 몫의 금액이 입력된 채로 Venmo, PayPal 또는 Cash App이 열려요. 돈은 Splitea를 거치지 않아요.",
        tagline: "요청 · 입금 · 끝",
      },
    ],
    pills: {
      contact: "연락처를 탭",
      items: "항목을 탭",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "어떤 앱으로든 요청",
      paid: "각자 편한 방법으로 받기",
    },
    stepGo: (n: number, label: string) => `${n}단계로 이동: ${label}`,
    play: "데모 재생",
    pause: "데모 일시정지",
    videoLabel: "항목 배정: 연락처를 탭한 다음, 그 사람이 먹은 항목을 탭해요.",
    endTitle: "다음 저녁 모임에서 써 보세요.",
    endNote: "다운로드는 무료예요.",
  },
  send: {
    title: "[[링크]]만 보내요.\n친구가 골라요.",
    tagline: "친구는 앱 없이 · 가입 없이",
    body: "라이브 링크 하나를 Splitea 미리보기 카드와 함께 메시지, WhatsApp, Mail로 공유하세요. 친구는 Android를 포함한 어떤 브라우저에서든 링크를 열고 자기가 먹은 항목을 탭해요. 링크가 있는 사람은 모두 서로의 선택을 실시간으로 봐요. 다 고르고 나면 편집 잠금으로 마무리하세요.",
    line: "이 페이지 맨 위의 휴대폰 화면이 바로 그 페이지예요.",
    tryIt: "체험해 보기",
    connected: "연결됨 (3)",
    anyBrowser: "어떤 브라우저에서든 열려요",
    cardAlt: "채팅에 표시된 Splitea 링크 미리보기 카드.",
  },
  trips: {
    title: "[[여행]] 경비,\n한 장에 정리.",
    tagline: "모임 · 공유 · 정산",
    body: "여행 영수증을 폴더 하나에 모으세요. 폴더 요약은 폴더 안 모든 정산에서 사람별 합계를 더해 주고, 같은 사람의 번호가 다르게 저장되어 있어도 한 사람으로 묶어 줘요. 그다음 폴더 내보내기로 각자의 합계가 담긴 PDF 하나를 공유하세요.",
    alt: "영수증 여러 장이 담긴 여행 폴더.",
  },
  digital: {
    title: "[[전자]] 영수증?\n더 쉬워요.",
    tagline: "Safari · 공유 · Splitea",
    body: "영수증을 웹 페이지나 PDF로 받으셨나요? Safari, 파일, Mail에서 공유한 뒤 Splitea를 선택하세요. 웹 페이지는 읽기 전에 실제 텍스트가 담긴 PDF로 바뀌어요. 로그인이 필요한 페이지라면 Safari의 PDF 옵션을 사용하세요.",
    pills: ["공유를 탭", "Splitea를 선택"],
    alt: "앱 목록에 Splitea가 보이는 iOS 공유 시트.",
  },
  abroad: {
    title: "해외 영수증?\n[[내 통화]]로 나눠요.",
    tagline: "환산 · 번역 · 정산",
    body: "카드 명세서의 금액, 직접 정한 환율, 또는 오늘의 환율로 정산을 내 통화로 환산하세요. 환산된 몫을 더해도 환산된 합계와 딱 맞고, 친구는 자기 페이지에서 환율을 볼 수 있어요. 엔화나 원화처럼 소수점 아래 단위가 없는 통화도 문제없어요.",
    translateBefore: "다른 문자로 적힌 항목 이름은 ",
    translateExample: "寿司",
    translateExampleLang: "ja",
    translateAfter: " (스시)처럼 내 언어 번역이 함께 표시돼요. 앱은 10개 언어를 지원해요.",
    alt: "페소를 달러로 환산하는 통화 환산 시트.",
    payTitle: "친구는 이미 쓰는 앱으로 결제해요.",
    regions: [
      { title: "미국", text: "Venmo, Cash App, PayPal, Revolut, ATH Móvil. Venmo는 금액과 메모가 입력된 채로 열려요." },
      { title: "푸에르토리코", text: "ATH Móvil, Venmo, Cash App, PayPal, Revolut. ATH Móvil은 친구가 금액을 직접 입력해요." },
      { title: "영국 및 아일랜드", text: "Monzo, Revolut, PayPal. 금액이 입력된 채로 열려요." },
      { title: "유럽", text: "Revolut, PayPal. 금액이 입력된 채로 열려요." },
      { title: "인도", text: "루피로 결제하는 Google Pay UPI. 금액이 입력된 채로 열려요." },
    ],
    prev: "이전 지역",
    next: "다음 지역",
    footnote: "PayPal은 대부분의 국가에서 쓸 수 있어요. 결제 앱이 설정되어 있지 않아도 친구는 자기 몫을 결제 완료로 표시할 수 있어요. Apple Pay, Apple Cash, Zelle은 지원하지 않아요.",
  },
  privacy: {
    title: "내 영수증은\n내 [[iCloud]]에.",
    tagline: "광고 없음 · 추적 없음 · 내 iCloud",
    body: "저장한 정산, 폴더, 프로필은 내 iCloud를 통해 동기화되고, Splitea 서버에는 영수증 라이브러리가 보관되지 않아요. 연락처 사진은 iPhone에만 남고, 이름은 그 사람이 포함된 정산을 공유할 때만 기기 밖으로 나가요. 기기 밖으로 나가는 정보는 다음과 같아요.",
    facts: [
      {
        title: "읽기만 하고, 보관하지 않아요.",
        text: "영수증을 읽기 위해 사진이 Splitea 서버와 AI 모델(현재 Google Gemini)로 전송돼요. 스캔 서비스는 이미지를 보관하지 않아요. 다만 스캔마다 계정, 앱 및 iOS 버전, 국가가 담긴 기록은 남겨요. 위치 접근을 허용하면 세율을 고르기 위해 대략적인 위치도 함께 전송돼요.",
      },
      {
        title: "링크는 30일 후 만료돼요.",
        text: "정산을 공유하면 사본이 Splitea 공유 서버로 전송돼요. 사본에는 항목과 금액, 영수증 사진, 정산에 포함된 사람들의 이름과 전화번호, 내 결제 앱 사용자 이름이 담겨요. 링크는 만든 날로부터 30일 후 만료돼요.",
      },
      {
        title: "광고도, 추적도 없어요.",
        text: "앱에는 광고, 추적 SDK, 타사 패키지가 없어요. 웹 페이지는 쿠키 없이 Cloudflare Web Analytics로 방문 수만 집계해요.",
      },
      {
        title: "프로필은 삭제할 때까지 보관돼요.",
        text: "이름, 사진, 전화번호, 이메일, 결제 앱 사용자 이름은 친구가 나를 찾고 돈을 보낼 수 있도록 Splitea 서버에 보관되고, 앱은 정산에 있는 전화번호를 이 정보와 대조해요. 설정에서 계정을 삭제하면 내 공유가 종료되고 이 프로필이 삭제되며, iPhone과 iCloud에서 영수증이 지워져요.",
      },
    ],
    link: "개인정보 처리방침 읽기",
  },
  pricing: {
    title: "무료 스캔 [[3]]회로 시작해요.",
    tagline: "다운로드 무료 · 무료 스캔 3회",
    body: "Splitea는 무료로 다운로드할 수 있고, 모든 계정에 무료 스캔 3회가 제공돼요. 매달 3회가 아니라 총 3회예요. 그 이후에는 스캔하든, 사진이나 PDF를 가져오든, 다른 앱에서 공유해 넣든, 직접 입력하든 새 영수증을 추가하려면 Splitea Unlimited가 필요해요. 비용 나누기, 링크 공유, 실시간 편집, 정산, 폴더, PDF 내보내기, 통화 환산은 구독 없이 쓸 수 있어요. 친구가 링크를 여는 건 언제나 무료예요.",
    plan: "Splitea Unlimited",
    checks: ["스캔, 가져오기, 직접 입력까지 영수증 무제한", "강조 색상 직접 고르기"],
    price: (monthly: string, yearly: string) => `미국 기준 월 ${monthly} 또는 연 ${yearly}.`,
    vary: "가격은 국가마다 달라요.",
    fine: "영수증을 읽지 못하면 스캔 횟수가 차감되지 않고, 같은 사진을 다시 스캔해도 두 번 차감되지 않아요.",
  },
  faq: {
    title: "궁금한 점, [[답변]]드려요.",
    items: [
      {
        q: "친구도 Splitea나 iPhone이 있어야 하나요?",
        a: "아니요. 링크는 Android 휴대폰과 노트북을 포함해 어떤 브라우저에서든 열리고, 앱도 계정도 필요 없어요. 페이지는 10개 언어로 제공되고, 친구는 자기 결제 앱으로 결제해요.",
      },
      {
        q: "계정이 필요한가요?",
        a: "네. 스캔하고 공유하려면 Apple로 로그인해야 하고, 사람을 고를 수 있도록 Splitea가 연락처 접근 권한을 요청해요. 전체 접근과 제한된 접근 모두 사용할 수 있어요.",
      },
      {
        q: "구독하지 않으면 무엇을 할 수 있나요?",
        a: "이미 있는 영수증으로는 모든 걸 할 수 있어요. 링크 공유, 실시간 편집, 정산, 폴더, PDF 내보내기, 통화 환산은 구독 없이 쓸 수 있고, 친구가 보내 준 정산도 마찬가지예요. 무료 스캔 3회를 다 쓰고 나면 카메라, 사진, PDF, 공유 시트, 직접 입력 중 어떤 방법이든 새 영수증을 추가하려면 Splitea Unlimited가 필요해요. Splitea Unlimited에서는 강조 색상도 직접 고를 수 있어요.",
      },
      {
        q: "Splitea가 돈을 처리하나요?",
        a: "아니요. Splitea는 돈을 직접 보내거나 받지 않고, 친구의 결제 앱이나 링크를 열어 줄 뿐이에요. 나라에 따라 Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay UPI를 지원해요. ATH Móvil은 친구가 금액을 직접 입력하고, 나머지는 금액이 입력된 채로 열려요. Apple Pay, Apple Cash, Zelle은 지원하지 않지만, 그래도 친구는 자기 몫을 결제 완료로 표시할 수 있어요.",
      },
      {
        q: "영수증을 잘못 읽으면 어떻게 하나요?",
        a: "Splitea는 소계, 세금, 합계를 인쇄된 영수증과 대조하고, 맞지 않으면 알려 줘요. 항목을 탭하면 설명, 가격, 세금을 바꿀 수 있어요. 사진에 빛 반사나 흔들림이 있을 때, 영수증이 잘렸을 때, 계산서 대신 메뉴판을 찍었을 때, 한 사진에 영수증이 여러 장 담겼을 때도 카메라가 알려 줘요.",
      },
      {
        q: "미국 밖에서도 쓸 수 있나요?",
        a: "네. Splitea는 영국, 멕시코, 일본, 독일, 인도, 브라질, 한국 등 여러 나라의 App Store에서 받을 수 있어요. 엔화나 원화처럼 소수점 아래 단위가 없는 통화를 포함해 영수증의 통화 그대로 나누고, 일본이나 EU처럼 세금이 이미 포함된 영수증도 처리하고, 정산을 내 통화로 환산할 수도 있어요.",
      },
      {
        q: "iOS 27도 더치페이를 지원하는데, 왜 Splitea를 써야 하나요?",
        a: "Apple의 더치페이 기능은 iOS에 내장되어 있고 무료예요. 이 기능은 Apple Cash로 작동하며, Apple Cash는 미국 50개 주, 워싱턴 D.C., 푸에르토리코에서 iPhone, iPad 또는 Apple Watch를 가진 18세 이상 미국 거주자만 쓸 수 있어요. Splitea에서는 친구가 어떤 휴대폰이나 컴퓨터에서든 링크를 열고 Venmo, PayPal, ATH Móvil 같은 앱으로 결제할 수 있고, 여러 나라에서 쓸 수 있고, 스캔에 Apple Intelligence도 필요 없어요. 친구마다 실시간으로 자기 항목을 고르고, 항목마다 현지 세금이 붙고, 여행 영수증은 PDF 하나로 합산돼요. Splitea는 무료 스캔 3회를 제공하고, 그 후에는 구독이 필요해요.",
      },
      {
        q: "공유 링크는 얼마나 유지되나요?",
        a: "공유 링크는 만든 날로부터 30일 후 만료돼요. 내 사본은 라이브러리에 그대로 남아요.",
      },
      {
        q: "어떤 iPhone에서 쓸 수 있나요?",
        a: "iOS 26 이상을 실행하는 모든 iPhone에서 쓸 수 있어요. iPad, Mac, Android 앱은 없으니, 다른 기기를 쓰는 친구는 브라우저에서 링크를 열면 돼요.",
      },
    ],
    dataQ: "내 데이터는 어디에 있나요?",
    dataBefore: "저장한 영수증, 폴더, 프로필은 내 iCloud를 통해 동기화돼요. Splitea 서버로 가는 정보와 보관 기간은 위의 ",
    dataLink: "개인정보 섹션",
    dataAfter: "에 정리되어 있어요.",
  },
  get: {
    pronunciation: "/ 스플리·테·아 /",
    title: "모든 영수증, [[한 번의 탭]]으로.",
    body: "저장한 정산은 모두 라이브러리에 남고, 내 iCloud로 동기화돼요. 하나를 열면 누가 정산했는지 볼 수 있어요.",
    small: "다운로드 무료, 무료 스캔 3회 제공. iPhone 전용, iOS 26 이상.",
    qrCaption: "컴퓨터로 보고 계신가요? iPhone 카메라로 스캔하세요.",
    tagline: "Splitea · 정산의 정석",
    gridAlt: "모든 정산 라이브러리.",
    listAlt: "목록으로 본 모든 정산 라이브러리.",
  },
  footer: {
    origin: "Splitea · 푸에르토리코에서 제작",
    languages: "언어",
    privacy: "개인정보 처리방침",
    terms: "이용약관",
    appStore: "App Store",
    legal: [
      "Apple, Apple 로고, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash 및 Apple Intelligence는 미국 및 기타 국가와 지역에서 등록된 Apple Inc.의 상표입니다. App Store는 Apple Inc.의 서비스 상표입니다.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp 및 Zelle은 각 소유자의 상표입니다. Splitea는 이들과 제휴 관계가 없습니다.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "App Store에서 Splitea 다운로드",
};

export default ko;
