import type { Copy } from "./en";

const ptBR: Copy = {
  meta: {
    title: "Splitea para iPhone: divida a conta com amigos, até o centavo",
    description: "Fotografe o recibo, toque em quem pediu o quê e mande um link. Os amigos escolhem os itens em qualquer navegador, sem app, e as partes somam o total exato.",
    ogTitle: "Splitea: divida a conta até o último centavo",
    ogDescription: "Fotografe o recibo, toque em quem pediu o quê e mande um link. Os amigos escolhem os itens em qualquer navegador. Para iPhone.",
    ogImageAlt: "Divida a conta até o último centavo. A tela Atribuir itens do Splitea em um iPhone, com as indicações 1 Toque em um contato e 2 Toque nos itens.",
    ogTagline: "Para iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "Como funciona" },
      { id: "trips", label: "Viagens" },
      { id: "abroad", label: "No exterior" },
      { id: "privacy", label: "Privacidade" },
      { id: "pricing", label: "Preços" },
    ],
    cta: "Obter Splitea",
    dismiss: "Fechar",
    qrLine: "Escaneie com a câmera do iPhone para baixar o Splitea.",
    qrLink: "Abrir a página na App Store",
  },
  hero: {
    titleTop: "Divida a conta",
    titleBottom: "até o [[centavo]].",
    tagline: "Cada centavo no seu lugar",
    body: "Fotografe o recibo, toque em quem pediu o quê e mande o link. Os amigos escolhem os próprios itens em qualquer navegador e acertam com você. Eles não precisam do app.",
    noteTop: "Grátis para baixar.",
    noteBottom: "Para iPhone com iOS 26 ou posterior.",
    android: "Usa Android? Os links do Splitea abrem direto no navegador. O app é para iPhone.",
    pills: ["Toque em um contato", "Toque nos itens"],
    tryIt: "Experimente ao vivo",
    done: "Concluído",
    demoLabel: "Demo ao vivo · a página que seus amigos abrem",
    demoNote: "Esse celular está ao vivo. É exatamente a página que seus amigos abrem.",
    qrCaption: "Está no computador? Escaneie com a câmera do iPhone.",
  },
  how: {
    title: "Fotografe, toque, envie.\n[[Receba]] de volta.",
    tagline: "Escanear · Atribuir · Impostos · Acertar",
    body: "Fotografe a conta, toque em quem pediu o quê, e o Splitea calcula impostos, gorjeta e cada centavo. Depois, você recebe dos amigos do jeito deles.",
    steps: [
      {
        rail: "Escanear",
        title: "Fotografe o [[recibo]].",
        body: "O Splitea lê os itens e os preços para você. Se um reflexo ou uma foto tremida esconder um preço, a câmera avisa.",
        tagline: "Câmera · Fotos · PDF",
      },
      {
        rail: "Atribuir",
        title: "Toque em um contato.\nToque nos [[itens]].",
        body: "Os pratos compartilhados são divididos entre quem pediu, e um toque atribui um item a todos.",
        tagline: "Quem pediu o quê",
      },
      {
        rail: "Impostos",
        title: "Impostos [[locais]], automáticos.",
        body: "Cada item recebe a própria alíquota, conferida com o imposto impresso. Aqui: 7% no mofongo, 11,5% no Old Fashioned.",
        tagline: "Zero cálculos à mão",
      },
      {
        rail: "Acertar",
        title: "Tudo acertado, [[simples]].",
        body: "Os amigos tocam em Pagar para abrir o Venmo, o PayPal ou o Cash App com o valor que devem. O Splitea nunca mexe no dinheiro.",
        tagline: "Cobre · Receba · Repita",
      },
    ],
    pills: {
      contact: "Toque em um contato",
      items: "Toque nos itens",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "Cobre por qualquer app",
      paid: "Receba do jeito deles",
    },
    stepGo: (n: number, label: string) => `Ir para o passo ${n}: ${label}`,
    play: "Reproduzir a demo",
    pause: "Pausar a demo",
    videoLabel: "Atribuir itens: toque em um contato e depois nos itens que a pessoa pediu.",
    endTitle: "Experimente no seu próximo jantar.",
    endNote: "Grátis para baixar.",
  },
  send: {
    title: "Manda o [[link]].\nEles escolhem.",
    tagline: "Sem app · Sem cadastro para os amigos",
    body: "Compartilhe um único link ao vivo pelo app Mensagens, pelo WhatsApp ou por e-mail, com um cartão de prévia do Splitea. Os amigos abrem em qualquer navegador, inclusive no Android, e tocam no que pediram. Quem tem o link vê cada escolha na hora, e você pode bloquear a edição quando terminar.",
    line: "O celular no topo desta página mostra essa mesma página.",
    tryIt: "Experimente",
    connected: "Conectados (3)",
    anyBrowser: "Abre em qualquer navegador",
    cardAlt: "Um cartão de prévia de link do Splitea em uma conversa.",
  },
  trips: {
    title: "Uma [[viagem]].\nUm resumo.",
    tagline: "Agrupe · Exporte · Acerte",
    body: "Coloque os recibos de uma viagem em uma pasta. O Resumo da pasta soma o total de cada pessoa em todas as divisões e reconhece a mesma pessoa mesmo quando o número dela está salvo de outro jeito. Depois, com Exportar pasta, você compartilha um só PDF com o total de cada um.",
    alt: "Uma pasta de viagem com vários recibos.",
  },
  digital: {
    title: "Recibo [[digital]]?\nAinda mais fácil.",
    tagline: "Safari · Compartilhar · Splitea",
    body: "Recebeu o recibo como página web ou PDF? Compartilhe pelo Safari, pelo app Arquivos ou pelo Mail e escolha o Splitea. As páginas web viram um PDF com texto real antes da leitura. Se a página exigir login, use a opção de PDF do Safari.",
    pills: ["Toque em Compartilhar", "Escolha o Splitea"],
    alt: "O menu de compartilhamento do iOS com o Splitea na fileira de apps.",
  },
  abroad: {
    title: "Conta em outra moeda?\nDivida na [[sua]].",
    tagline: "Converta · Traduza · Acerte",
    body: "Converta uma divisão para a sua moeda usando o valor da fatura do cartão, a sua própria taxa ou a taxa de mercado do dia. As partes convertidas continuam somando o total convertido, e os amigos veem a taxa na página deles. Moedas sem centavos, como o iene e o won, também funcionam.",
    translateBefore: "Nomes de itens escritos em outro alfabeto vêm com tradução no seu idioma, como ",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: " (Bibimbap). O app fala 10 idiomas.",
    alt: "A tela de conversão de moeda, de pesos para dólares.",
    payTitle: "Os amigos pagam com o app que já usam.",
    regions: [
      { title: "Estados Unidos", text: "Venmo, Cash App, PayPal, Revolut e ATH Móvil. O Venmo abre com o valor e uma nota já preenchidos." },
      { title: "Porto Rico", text: "ATH Móvil, Venmo, Cash App, PayPal e Revolut. No ATH Móvil, seu amigo digita o valor." },
      { title: "Reino Unido e Irlanda", text: "Monzo, Revolut e PayPal, com o valor já preenchido." },
      { title: "Europa", text: "Revolut e PayPal, com o valor já preenchido." },
      { title: "Índia", text: "Google Pay UPI em rúpias, com o valor já preenchido." },
    ],
    prev: "Região anterior",
    next: "Próxima região",
    footnote: "O PayPal funciona na maioria dos países. Nenhum app de pagamento configurado? Os amigos ainda podem marcar a parte deles como paga. Apple Pay, Apple Cash e Zelle não são compatíveis.",
  },
  privacy: {
    title: "Seus recibos.\nSeu [[iCloud]].",
    tagline: "Sem anúncios · Sem rastreadores · Seu iCloud",
    body: "As divisões salvas, as pastas e o seu perfil são sincronizados pelo seu próprio iCloud, e os servidores do Splitea não guardam sua biblioteca de recibos. As fotos dos contatos ficam no seu iPhone, e um nome só sai dele quando você compartilha uma divisão que inclui essa pessoa. Veja abaixo o que sai dele.",
    facts: [
      {
        title: "Lido, não guardado.",
        text: "Para ler um recibo, a foto vai para o servidor do Splitea e para um modelo de IA (atualmente o Google Gemini). O serviço de escaneamento não guarda a imagem. Ele mantém um registro de cada escaneamento com a sua conta, as versões do app e do iOS e o país. Se você permitir o acesso à localização, uma localização aproximada vai junto para escolher a alíquota do imposto.",
      },
      {
        title: "Os links expiram após 30 dias.",
        text: "Quando você compartilha uma divisão, uma cópia vai para o servidor de compartilhamento do Splitea: os itens e os valores, a foto do recibo, os nomes e números de telefone das pessoas da divisão e os seus nomes de usuário de pagamento. O link expira 30 dias depois de criado.",
      },
      {
        title: "Sem anúncios. Sem rastreadores.",
        text: "O app não tem anúncios, SDKs de rastreamento nem pacotes de terceiros. Nossas páginas web só contam visitas, com o Cloudflare Web Analytics, que não usa cookies.",
      },
      {
        title: "Seu perfil, até você excluí-lo.",
        text: "Seu nome, sua foto, seu número de telefone, seu e-mail e seus nomes de usuário de pagamento ficam nos servidores do Splitea para que os amigos possam encontrar e pagar você, e o app compara os números de telefone das suas divisões com esses dados. Excluir a conta em Ajustes encerra seus compartilhamentos, remove esse perfil e apaga seus recibos do iPhone e do iCloud.",
      },
    ],
    link: "Ler a política de privacidade",
  },
  pricing: {
    title: "Comece com [[3]] escaneamentos grátis.",
    tagline: "Grátis para baixar · 3 escaneamentos grátis",
    body: "O Splitea é grátis para baixar, e toda conta ganha 3 escaneamentos grátis: 3 no total, não 3 por mês. Depois disso, adicionar um novo recibo exige o Splitea Unlimited, seja escaneando, importando uma foto ou um PDF, compartilhando com o Splitea ou digitando à mão. Divisão, links compartilhados, edição ao vivo, acerto de contas, pastas, exportação em PDF e conversão de moeda não exigem assinatura. Abrir um link é sempre grátis para os seus amigos.",
    plan: "Splitea Unlimited",
    checks: ["Recibos ilimitados, escaneados, importados ou digitados", "Cor de destaque personalizada"],
    price: (monthly: string, yearly: string) => `${monthly} por mês ou ${yearly} por ano nos EUA.`,
    vary: "Os preços variam de acordo com o país.",
    fine: "Uma leitura que falha não gasta um escaneamento, e escanear a mesma foto de novo não conta duas vezes.",
  },
  faq: {
    title: "Perguntas, [[respondidas]].",
    items: [
      {
        q: "Meus amigos precisam do Splitea ou de um iPhone?",
        a: "Não. Seu link abre em qualquer navegador, inclusive em celulares Android e notebooks, sem app e sem conta. A página está disponível em 10 idiomas, e eles pagam com o próprio app de pagamento.",
      },
      {
        q: "Preciso de uma conta?",
        a: "Sim. Você entra com a Apple para escanear e compartilhar, e o Splitea pede acesso aos Contatos para você escolher as pessoas. Funciona com acesso total ou limitado.",
      },
      {
        q: "O que posso fazer sem assinar?",
        a: "Tudo com os recibos que você já tem. Links compartilhados, edição ao vivo, acerto de contas, pastas, exportação em PDF e conversão de moeda não exigem assinatura, e as divisões que os amigos enviam para você também não. Depois dos seus 3 escaneamentos grátis, adicionar um novo recibo, pela câmera, por foto, PDF, menu de compartilhamento ou à mão, exige o Splitea Unlimited, que também libera uma cor de destaque personalizada.",
      },
      {
        q: "O Splitea mexe no dinheiro?",
        a: "Não. O Splitea nunca movimenta dinheiro. Ele abre o app ou o link de pagamento do seu amigo: Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo ou Google Pay UPI, dependendo do seu país. Cada um abre com o valor já preenchido, exceto o ATH Móvil, em que seu amigo digita o valor. Apple Pay, Apple Cash e Zelle não são compatíveis, mas os amigos ainda podem marcar a parte deles como paga.",
      },
      {
        q: "E se um recibo for lido errado?",
        a: "O Splitea confere o subtotal, o imposto e o total com o recibo impresso e avisa quando eles não batem. Toque em qualquer item para alterar a descrição, o preço ou o imposto. A câmera também avisa quando uma foto tem reflexo ou está tremida, corta o recibo, mostra um cardápio em vez da conta ou tem vários recibos.",
      },
      {
        q: "Funciona fora dos EUA?",
        a: "Sim. O Splitea está na App Store em muitos países, incluindo Reino Unido, México, Japão, Alemanha, Índia, Brasil e Coreia. Ele divide na moeda do recibo, inclusive nas que não têm centavos, como o iene e o won, lida com recibos que já incluem o imposto, como os do Japão e da UE, e pode converter uma divisão para a sua moeda.",
      },
      {
        q: "O iOS 27 divide contas. Por que usar o Splitea?",
        a: "O recurso de divisão de contas da Apple vem integrado e é gratuito. Ele usa o Apple Cash, que funciona nos 50 estados dos EUA, em Washington, D.C. e em Porto Rico, para residentes dos EUA com 18 anos ou mais e um iPhone, iPad ou Apple Watch. Com o Splitea, os amigos abrem o seu link em qualquer celular ou computador e pagam com apps como Venmo, PayPal ou ATH Móvil. O Splitea funciona em muitos países, e escanear não exige a Apple Intelligence. Cada amigo escolhe os próprios itens ao vivo, cada item recebe o imposto local, e os recibos de uma viagem são somados em um só PDF. O Splitea dá 3 escaneamentos grátis e depois exige uma assinatura.",
      },
      {
        q: "Quanto tempo duram os links compartilhados?",
        a: "Os links compartilhados expiram 30 dias depois de criados. A sua cópia continua na sua biblioteca.",
      },
      {
        q: "Em quais iPhones ele funciona?",
        a: "Em qualquer iPhone com iOS 26 ou posterior. Não há app para iPad, Mac ou Android, então os amigos em outros aparelhos usam o link no navegador.",
      },
    ],
    dataQ: "Onde ficam meus dados?",
    dataBefore: "Os recibos salvos, as pastas e o seu perfil são sincronizados pelo seu próprio iCloud. A ",
    dataLink: "seção de privacidade",
    dataAfter: " acima lista o que vai para os servidores do Splitea e por quanto tempo.",
  },
  get: {
    pronunciation: "/ spli·TÊ·a /",
    title: "Cada recibo, a [[um toque]].",
    body: "Cada divisão que você salva fica na sua biblioteca, sincronizada pelo seu próprio iCloud. Abra uma para ver quem já pagou.",
    small: "Grátis para baixar, com 3 escaneamentos grátis. Só para iPhone, iOS 26 ou posterior.",
    qrCaption: "Está no computador? Escaneie com a câmera do iPhone.",
    tagline: "Splitea · Sua conta, resolvida",
    gridAlt: "A biblioteca Todos os splits.",
    listAlt: "A biblioteca Todos os splits em lista.",
  },
  footer: {
    origin: "Splitea · Feito em Porto Rico",
    languages: "Idioma",
    privacy: "Privacidade",
    terms: "Termos",
    appStore: "App Store",
    legal: [
      "Apple, o logotipo da Apple, iPhone, iPad, Mac, Apple Watch, iCloud, Safari, Apple Pay, Apple Cash e Apple Intelligence são marcas comerciais da Apple Inc., registradas nos EUA e em outros países e regiões. App Store é uma marca de serviço da Apple Inc.",
      "Venmo, Cash App, PayPal, ATH Móvil, Revolut, Monzo, Google Pay, Gemini, Android, WhatsApp e Zelle são marcas comerciais de seus respectivos proprietários. O Splitea não é afiliado a eles.",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "Baixar o Splitea na App Store",
};

export default ptBR;
