import type { Copy } from "./en";

const zhHans: Copy = {
  meta: {
    title: "Splitea：iPhone 分账 App，拍下收据和朋友 AA，精确到分",
    description: "拍下收据，点选谁吃了什么，再发一个链接。朋友无需安装 App，在任意浏览器里选好自己的项目，每个人的份额加起来正好等于账单总额。",
    ogTitle: "Splitea：分账精确到每一分",
    ogDescription: "拍下收据，点选谁吃了什么，发个链接。朋友在任意浏览器里选自己的项目。适用于 iPhone。",
    ogImageAlt: "和朋友分账，每一分都不差。iPhone 上 Splitea 的“分配项目”界面，标注着“1 点击联系人”和“2 点击TA的项目”。",
    ogTagline: "适用于 iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "使用方法" },
      { id: "trips", label: "旅行" },
      { id: "abroad", label: "海外" },
      { id: "privacy", label: "隐私" },
      { id: "pricing", label: "价格" },
    ],
    cta: "获取 Splitea",
    dismiss: "关闭",
    qrLine: "用 iPhone 相机扫码，获取 Splitea。",
    qrLink: "打开 App Store 页面",
  },
  hero: {
    titleTop: "和朋友分账，",
    titleBottom: "每一[[分]]都不差。",
    tagline: "一分一厘都算清楚",
    body: "拍下收据，点一点分清谁吃了什么，再把链接发出去。朋友在任意浏览器里选好自己的项目，然后把钱还给你。他们不需要下载 App。",
    noteTop: "免费下载。",
    noteBottom: "适用于 iOS 26 或更高版本的 iPhone。",
    android: "用的是 Android？Splitea 链接可以直接在浏览器中打开。App 仅适用于 iPhone。",
    pills: ["点击联系人", "点击TA的项目"],
    tryIt: "动手试一试",
    done: "完成",
    demoLabel: "实时演示 · 朋友打开的页面",
    demoNote: "这部手机可以直接操作，里面就是朋友打开的那个页面。",
    qrCaption: "在用电脑？用 iPhone 相机扫一扫。",
  },
  how: {
    title: "拍照，点选，发送。\n坐等[[收款]]。",
    tagline: "扫描 · 分配 · 税费 · 结清",
    body: "拍下账单，点选谁吃了什么，Splitea 会算好税费、小费和每一分钱。然后朋友用自己习惯的方式还你钱。",
    steps: [
      {
        rail: "扫描",
        title: "拍下[[收据]]。",
        body: "Splitea 会帮你读取项目和价格。如果反光或模糊遮住了价格，相机会提醒你。",
        tagline: "相机 · 照片 · PDF",
      },
      {
        rail: "分配",
        title: "点击联系人。\n点击TA的[[项目]]。",
        body: "几个人分着吃的菜，由吃过的人分摊；点一下，就能把一个项目分给所有人。",
        tagline: "谁吃了什么",
      },
      {
        rail: "税费",
        title: "[[当地]]税率，\n自动套用。",
        body: "每个项目都有自己的税率，并会与收据上印的税额核对。比如这里：Mofongo 税率 7%，Old Fashioned 税率 11.5%。",
        tagline: "告别手动算账",
      },
      {
        rail: "结清",
        title: "账单结清，\n就这么[[简单]]。",
        body: "朋友点击“支付”，就会打开 Venmo、PayPal 或 Cash App，并带上自己的应付金额。Splitea 从不经手钱款。",
        tagline: "收款 · 到账 · 再来",
      },
    ],
    pills: {
      contact: "点击联系人",
      items: "点击TA的项目",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "用任何应用发起收款",
      paid: "按TA习惯的方式收款",
    },
    stepGo: (n: number, label: string) => `前往第 ${n} 步：${label}`,
    play: "播放演示",
    pause: "暂停演示",
    videoLabel: "分配项目：点击联系人，然后点击TA吃过的项目。",
    endTitle: "下次聚餐就试试吧。",
    endNote: "免费下载。",
  },
  send: {
    title: "发个[[链接]]，\n各选各的。",
    tagline: "朋友免下载 · 免注册",
    body: "通过“信息”、WhatsApp 或“邮件”分享一个实时链接，并附带 Splitea 预览卡片。朋友在任意浏览器中打开，包括 Android 手机，点选自己吃过的项目。拿到链接的每个人都能实时看到每一次选择，分完后你还可以锁定编辑。",
    line: "本页顶部那部手机里显示的，就是这个页面。",
    tryIt: "试一试",
    connected: "已连接 (3)",
    anyBrowser: "任意浏览器都能打开",
    cardAlt: "聊天中的 Splitea 链接预览卡片。",
  },
  trips: {
    title: "一趟[[旅行]]，\n一份账单。",
    tagline: "汇总 · 分享 · 收款",
    body: "把一趟旅行的收据放进一个文件夹。“文件夹摘要”会汇总每个人在所有分账中的总额，即使同一个人的电话号码保存格式不同，也能认出是同一个人。然后用“导出文件夹”分享一份包含每个人总额的 PDF。",
    alt: "装着多张收据的旅行文件夹。",
  },
  digital: {
    title: "[[电子]]收据？\n更省事。",
    tagline: "Safari · 分享 · Splitea",
    body: "收据是网页或 PDF？在 Safari 浏览器、“文件”或“邮件”中分享，然后选择 Splitea。网页会先转换成带真实文字的 PDF，再进行读取。如果页面需要登录，请使用 Safari 浏览器的 PDF 选项。",
    pills: ["点击分享", "选择 Splitea"],
    alt: "iOS 分享面板，App 一栏中有 Splitea。",
  },
  abroad: {
    title: "外币账单？\n用[[你的货币]]分账。",
    tagline: "换算 · 翻译 · 结清",
    body: "可以按银行卡账单上的金额、你自己设定的汇率或今日市场汇率，把一笔分账换算成你的本国货币。换算后的各人份额加起来仍然等于换算后的总额，朋友也能在自己的页面上看到汇率。日元、韩元这类没有小数位的货币也同样支持。",
    translateBefore: "用其他文字书写的项目名称会附上你所用语言的翻译，例如",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: "（拌饭）。App 支持 10 种语言。",
    alt: "货币换算面板，从比索换算成美元。",
    payTitle: "朋友用自己常用的 App 付款。",
    regions: [
      { title: "美国", text: "Venmo、Cash App、PayPal、Revolut 和 ATH Móvil。Venmo 打开时会自动填好金额和备注。" },
      { title: "波多黎各", text: "ATH Móvil、Venmo、Cash App、PayPal 和 Revolut。使用 ATH Móvil 时，需要朋友自己输入金额。" },
      { title: "英国和爱尔兰", text: "Monzo、Revolut 和 PayPal，均会自动填好金额。" },
      { title: "欧洲", text: "Revolut 和 PayPal，均会自动填好金额。" },
      { title: "印度", text: "Google Pay UPI，以卢比付款，会自动填好金额。" },
    ],
    prev: "上一个地区",
    next: "下一个地区",
    footnote: "PayPal 在大多数国家和地区都能用。没有设置付款 App？朋友仍然可以把自己的份额标记为已付。不支持 Apple Pay、Apple Cash 和 Zelle。",
  },
  privacy: {
    title: "你的收据，\n你的 [[iCloud]]。",
    tagline: "无广告 · 无跟踪 · 你的 iCloud",
    body: "已保存的分账、文件夹和你的个人资料通过你自己的 iCloud 同步，Splitea 的服务器不保存你的收据库。联系人照片只留在你的 iPhone 上，只有当你分享一笔包含某个人的分账时，这个人的名字才会离开你的 iPhone。以下是确实会离开 iPhone 的内容。",
    facts: [
      {
        title: "只读取，不保留。",
        text: "为了读取收据，照片会发送到 Splitea 的服务器和一个 AI 模型（目前为 Google Gemini）。扫描服务不会保留照片。它会为每次扫描保留一条记录，包含你的账户、App 和 iOS 版本以及国家或地区。如果你允许访问位置，扫描时还会附带大致位置，用于判断税率。",
      },
      {
        title: "链接 30 天后失效。",
        text: "当你分享一笔分账时，一份副本会发送到 Splitea 的分享服务器，包括项目和金额、收据照片、分账中各人的姓名和电话号码，以及你的付款用户名。链接会在创建 30 天后失效。",
      },
      {
        title: "无广告，无跟踪。",
        text: "App 没有广告，没有跟踪 SDK，也没有任何第三方代码库。我们的网页只用 Cloudflare Web Analytics 统计访问量，不使用 Cookie。",
      },
      {
        title: "你的个人资料，保留到你删除为止。",
        text: "你的姓名、头像、电话号码、电子邮件和付款用户名保存在 Splitea 的服务器上，方便朋友找到你并向你付款，App 也会把你分账中的电话号码与这些资料进行比对。在“设置”中删除账户会结束你的分享、移除这份个人资料，并从你的 iPhone 和 iCloud 中删除你的收据。",
      },
    ],
    link: "阅读隐私政策",
  },
  pricing: {
    title: "先免费扫描 [[3]] 次。",
    tagline: "免费下载 · 3 次免费扫描",
    body: "Splitea 可免费下载，每个账户都有 3 次免费扫描：总共 3 次，不是每月 3 次。之后，添加新收据需要 Splitea Unlimited，无论是扫描、导入照片或 PDF、从其他 App 分享进来，还是手动输入。分账、分享链接、实时编辑、结清、文件夹、PDF 导出和货币换算都不设付费限制。朋友打开链接始终免费。",
    plan: "Splitea Unlimited",
    checks: ["无限添加收据，扫描、导入或手动输入都可以", "自定义强调色"],
    price: (monthly: string, yearly: string) => `美国价格为每月 ${monthly} 或每年 ${yearly}。`,
    vary: "价格因国家或地区而异。",
    fine: "识别失败不会消耗扫描次数，重新扫描同一张照片也不会重复计次。",
  },
  faq: {
    title: "有问[[必答]]。",
    items: [
      {
        q: "朋友需要安装 Splitea 或使用 iPhone 吗？",
        a: "不需要。你的链接可以在任意浏览器中打开，Android 手机和笔记本电脑也行，无需 App，也无需账户。页面支持 10 种语言，朋友用自己的付款 App 付款。",
      },
      {
        q: "我需要账户吗？",
        a: "需要。扫描和分享前要先使用 Apple 登录，Splitea 还会请求访问通讯录，方便你选择要分账的人。完全访问或有限访问都可以。",
      },
      {
        q: "不订阅能做什么？",
        a: "你已有的收据，所有功能都能用。分享链接、实时编辑、结清、文件夹、PDF 导出和货币换算都不设付费限制，朋友发给你的分账也一样。用完 3 次免费扫描后，添加新收据（无论是用相机、照片、PDF、分享面板还是手动输入）都需要 Splitea Unlimited，订阅后还能解锁自定义强调色。",
      },
      {
        q: "Splitea 会经手钱款吗？",
        a: "不会。Splitea 从不转移任何钱款。它会打开朋友的付款 App 或链接：根据你所在的国家或地区，可以是 Venmo、Cash App、PayPal、ATH Móvil、Revolut、Monzo 或 Google Pay UPI。打开时都会自动填好金额，只有 ATH Móvil 需要朋友自己输入。不支持 Apple Pay、Apple Cash 和 Zelle，但朋友仍然可以把自己的份额标记为已付。",
      },
      {
        q: "收据读错了怎么办？",
        a: "Splitea 会把小计、税费和总计与收据上印的数字核对，不一致时会提醒你。点击任意项目即可更改它的描述、价格或税费。如果照片有反光或模糊、收据没拍全、拍的是菜单而不是账单，或者一张照片里有多张收据，相机也会提醒你。",
      },
      {
        q: "在美国以外能用吗？",
        a: "可以。Splitea 已在许多国家和地区的 App Store 上架，包括英国、墨西哥、日本、德国、印度、巴西和韩国。它按收据上的货币分账，包括日元、韩元这类没有小数位的货币；也能处理已含税的收据，比如日本和欧盟的收据；还可以把分账换算成你的本国货币。",
      },
      {
        q: "iOS 27 自带分账功能，为什么还要用 Splitea？",
        a: "Apple 的分账功能是系统内置的，而且免费。它依托 Apple Cash，而 Apple Cash 面向美国 50 个州、华盛顿特区和波多黎各年满 18 岁、使用 iPhone、iPad 或 Apple Watch 的美国居民。使用 Splitea，朋友可以在任意手机或电脑上打开你的链接，并用 Venmo、PayPal 或 ATH Móvil 等 App 付款；它在许多国家和地区都能用，扫描也不需要 Apple 智能。每位朋友实时挑选自己的项目，每个项目都按当地税率计税，一趟旅行的收据还能汇总成一份 PDF。Splitea 提供 3 次免费扫描，之后需要订阅。",
      },
      {
        q: "分享链接有效期多久？",
        a: "分享链接会在创建 30 天后失效。你自己的副本会一直保留在你的收据库中。",
      },
      {
        q: "支持哪些 iPhone？",
        a: "任何装有 iOS 26 或更高版本的 iPhone 都可以。没有 iPad、Mac 或 Android 版 App，所以使用其他设备的朋友可以在浏览器中打开链接。",
      },
    ],
    dataQ: "我的数据存在哪里？",
    dataBefore: "已保存的收据、文件夹和你的个人资料通过你自己的 iCloud 同步。上方的",
    dataLink: "隐私部分",
    dataAfter: "列出了哪些内容会发送到 Splitea 的服务器，以及会保留多久。",
  },
  get: {
    pronunciation: "/ spli·TE·a /",
    title: "每张收据，\n[[轻点]]即达。",
    body: "你保存的每笔分账都留在你的收据库中，并通过你自己的 iCloud 同步。打开任意一笔，就能看到谁已经付款。",
    small: "免费下载，含 3 次免费扫描。仅限 iPhone，需要 iOS 26 或更高版本。",
    qrCaption: "在用电脑？用 iPhone 相机扫一扫。",
    tagline: "Splitea · 帮你搞定账单",
    gridAlt: "“所有分账”收据库。",
    listAlt: "以列表形式显示的“所有分账”收据库。",
  },
  footer: {
    origin: "Splitea · 波多黎各出品",
    languages: "语言",
    privacy: "隐私",
    terms: "条款",
    appStore: "App Store",
    legal: [
      "Apple、Apple 标志、iPhone、iPad、Mac、Apple Watch、iCloud、Safari、Apple Pay、Apple Cash 和 Apple Intelligence 是 Apple Inc. 在美国及其他国家和地区注册的商标。App Store 是 Apple Inc. 的服务标记。",
      "Venmo、Cash App、PayPal、ATH Móvil、Revolut、Monzo、Google Pay、Gemini、Android、WhatsApp 和 Zelle 是其各自所有者的商标。Splitea 与上述公司没有任何关联。",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "在 App Store 下载 Splitea",
};

export default zhHans;
