import type { Copy } from "./en";

const zhHant: Copy = {
  meta: {
    title: "Splitea iPhone 分帳 App：拍收據和朋友分帳，精準到每一分",
    description: "和朋友分帳：拍下收據，點選誰點了什麼，再傳一個連結。朋友不用下載 App，用任何瀏覽器就能挑選自己的項目，每個人的份額加起來剛好等於總額。",
    ogTitle: "Splitea：分帳，每一分都不差",
    ogDescription: "拍下收據，點選誰點了什麼，傳個連結。朋友用任何瀏覽器挑選自己的項目。適用於 iPhone。",
    ogImageAlt: "一起分帳，每一分都不差。iPhone 上的 Splitea「分配項目」畫面，附有標註「1 點選聯絡人」和「2 點選對方的項目」。",
    ogTagline: "適用於 iPhone · splitea.app",
  },
  nav: {
    chapters: [
      { id: "how", label: "運作方式" },
      { id: "trips", label: "旅行" },
      { id: "abroad", label: "海外" },
      { id: "privacy", label: "隱私權" },
      { id: "pricing", label: "價格" },
    ],
    cta: "取得 Splitea",
    dismiss: "關閉",
    qrLine: "用 iPhone 相機掃描，即可取得 Splitea。",
    qrLink: "打開 App Store 頁面",
  },
  hero: {
    titleTop: "一起分帳，",
    titleBottom: "每一[[分]]都不差。",
    tagline: "一分一毫，都算清楚",
    body: "拍下收據，點選誰點了什麼，再把連結傳出去。朋友用任何瀏覽器挑選自己的項目，然後把錢還給你。他們不需要下載 App。",
    noteTop: "免費下載。",
    noteBottom: "適用於搭載 iOS 26 或以上版本的 iPhone。",
    android: "用 Android 手機？Splitea 連結會直接在瀏覽器中打開。App 僅適用於 iPhone。",
    pills: ["點選聯絡人", "點選對方的項目"],
    tryIt: "即時試用",
    done: "完成",
    demoLabel: "即時示範 · 朋友會打開的頁面",
    demoNote: "這支手機可以直接操作，正是朋友會打開的那個頁面。",
    qrCaption: "正在用電腦？用 iPhone 相機掃描。",
  },
  how: {
    title: "拍照、點選、傳送，\n等著[[收錢]]。",
    tagline: "掃描 · 分配 · 稅率 · 結清",
    body: "拍下帳單，點選誰點了什麼，Splitea 就會算好稅金、小費和每一分錢。接著朋友用自己習慣的方式把錢還給你。",
    steps: [
      {
        rail: "掃描",
        title: "拍下[[收據]]。",
        body: "Splitea 幫你讀取項目和價格。如果反光或模糊擋住了價格，相機會提醒你。",
        tagline: "相機 · 照片 · PDF",
      },
      {
        rail: "分配",
        title: "點選聯絡人，\n點選對方的[[項目]]。",
        body: "大家合點的菜，由吃到的人一起分攤；點一下，就能把一個項目分給所有人。",
        tagline: "誰點了什麼",
      },
      {
        rail: "稅率",
        title: "[[當地]]稅率，自動套用。",
        body: "每個項目都有自己的稅率，並與收據上印的稅額核對。以這張為例：Mofongo 7%，Old Fashioned 11.5%。",
        tagline: "告別手動算帳",
      },
      {
        rail: "結清",
        title: "帳單結清，就這麼[[簡單]]。",
        body: "朋友點一下「支付」，就會打開 Venmo、PayPal 或 Cash App，並自動帶入他們應付的金額。Splitea 從不經手任何款項。",
        tagline: "請款 · 收款 · 再來一次",
      },
    ],
    pills: {
      contact: "點選聯絡人",
      items: "點選對方的項目",
      place: "San Juan, PR",
      oldFashioned: "Old Fashioned",
      mofongo: "Mofongo",
      request: "用任何 App 請款",
      paid: "用朋友慣用的方式收款",
    },
    stepGo: (n: number, label: string) => `前往第 ${n} 步：${label}`,
    play: "播放示範",
    pause: "暫停示範",
    videoLabel: "分配項目：點選聯絡人，再點選對方點的項目。",
    endTitle: "下次聚餐就試試看。",
    endNote: "免費下載。",
  },
  send: {
    title: "傳個[[連結]]，\n朋友自己選。",
    tagline: "朋友免下載 · 免註冊",
    body: "透過「訊息」、WhatsApp 或「郵件」分享一個即時連結，對話中會顯示 Splitea 預覽卡片。朋友用任何瀏覽器打開（Android 也可以），點選自己點的項目。有連結的人都能即時看到每個人的選擇，完成後你還可以「鎖定編輯」。",
    line: "本頁頂端那支手機裡的，就是朋友打開的頁面。",
    tryIt: "試試看",
    connected: "已連接 (3)",
    anyBrowser: "任何瀏覽器都能打開",
    cardAlt: "聊天中的 Splitea 連結預覽卡片。",
  },
  trips: {
    title: "一趟[[旅行]]，\n一張總表。",
    tagline: "歸類 · 分享 · 收款",
    body: "把一趟旅行的收據放進同一個資料夾。「資料夾摘要」會加總每個人在所有分帳中的總額，就算同一個人的電話號碼存成不同格式，也能正確對上。接著用「匯出資料夾」，分享一份列出每個人總額的 PDF。",
    alt: "存放多張收據的旅行資料夾。",
  },
  digital: {
    title: "[[電子]]收據？\n更省事。",
    tagline: "Safari · 分享 · Splitea",
    body: "收到的是網頁或 PDF 收據？從 Safari、「檔案」或「郵件」分享，然後選擇 Splitea。網頁會先轉成保留原始文字的 PDF，再進行讀取。如果頁面需要登入，請使用 Safari 的 PDF 選項。",
    pills: ["點一下「分享」", "選擇 Splitea"],
    alt: "iOS 分享表單，App 列中有 Splitea。",
  },
  abroad: {
    title: "外幣帳單？\n用[[你的]]貨幣分帳。",
    tagline: "換算 · 翻譯 · 結清",
    body: "用信用卡帳單上的金額、你自己的匯率或今日匯率，把分帳換算成你的貨幣。換算後，每個人的份額加起來仍等於換算後的總額，朋友也會在自己的頁面上看到匯率。日圓、韓元這類沒有「分」的貨幣也適用。",
    translateBefore: "以其他文字書寫的項目名稱，會附上你所用語言的翻譯，例如",
    translateExample: "비빔밥",
    translateExampleLang: "ko",
    translateAfter: "（拌飯）。App 提供 10 種語言。",
    alt: "貨幣換算畫面，從披索換算成美元。",
    payTitle: "朋友用他們本來就在用的 App 付款。",
    regions: [
      { title: "美國", text: "Venmo、Cash App、PayPal、Revolut 和 ATH Móvil。打開 Venmo 時會自動帶入金額和備註。" },
      { title: "波多黎各", text: "ATH Móvil、Venmo、Cash App、PayPal 和 Revolut。使用 ATH Móvil 時，朋友需要自行輸入金額。" },
      { title: "英國和愛爾蘭", text: "Monzo、Revolut 和 PayPal，會自動帶入金額。" },
      { title: "歐洲", text: "Revolut 和 PayPal，會自動帶入金額。" },
      { title: "印度", text: "Google Pay UPI，以盧比付款，會自動帶入金額。" },
    ],
    prev: "上一個地區",
    next: "下一個地區",
    footnote: "PayPal 在大多數國家或地區都能使用。還沒設定付款 App？朋友仍然可以把自己的份額標記為已付。不支援 Apple Pay、Apple Cash 和 Zelle。",
  },
  privacy: {
    title: "你的收據，\n你的 [[iCloud]]。",
    tagline: "無廣告 · 無追蹤 · 你的 iCloud",
    body: "已儲存的分帳、資料夾和你的個人檔案會透過你自己的 iCloud 同步，Splitea 的伺服器不會保存你的收據庫。聯絡人照片只會留在你的 iPhone 上，只有當你分享的分帳中有某個人時，那個人的姓名才會離開你的手機。以下是確實會離開手機的資料。",
    facts: [
      {
        title: "讀取，但不保留。",
        text: "為了讀取收據，照片會傳送到 Splitea 的伺服器和一個 AI 模型（目前為 Google Gemini）。掃描服務不會保留照片，但會為每次掃描保留一筆紀錄，包含你的帳戶、App 和 iOS 版本，以及國家或地區。如果你允許取用位置，掃描時會一併傳送大約位置，用來判斷稅率。",
      },
      {
        title: "連結 30 天後失效。",
        text: "當你分享分帳時，會有一份副本傳送到 Splitea 的分享伺服器，內容包括項目和金額、收據照片、分帳中每個人的姓名和電話號碼，以及你的付款使用者名稱。連結會在建立 30 天後失效。",
      },
      {
        title: "無廣告，無追蹤。",
        text: "App 沒有廣告、沒有追蹤 SDK，也不含任何第三方程式庫。我們的網頁只透過 Cloudflare Web Analytics 計算造訪次數，這項工具不使用 Cookie。",
      },
      {
        title: "你的個人檔案，保留到你刪除為止。",
        text: "你的姓名、大頭貼、電話號碼、電子郵件和付款使用者名稱會保存在 Splitea 的伺服器上，讓朋友能找到你並付款給你；App 也會將你分帳中的電話號碼與這些資料比對。在「設定」中刪除帳戶，會結束你的分享、移除這份個人檔案，並從你的 iPhone 和 iCloud 中清除你的收據。",
      },
    ],
    link: "閱讀隱私權政策",
  },
  pricing: {
    title: "先免費掃描 [[3]] 次。",
    tagline: "免費下載 · 3 次免費掃描",
    body: "Splitea 可免費下載，每個帳戶都有 3 次免費掃描：總共 3 次，不是每月 3 次。之後，新增收據就需要 Splitea Unlimited，無論是掃描、匯入照片或 PDF、從其他 App 分享進來，還是手動輸入。分帳、分享連結、即時編輯、結清、資料夾、PDF 匯出和貨幣換算都不需要訂閱。朋友打開連結永遠免費。",
    plan: "Splitea Unlimited",
    checks: ["無限新增收據，掃描、匯入或手動輸入皆可", "自訂強調色"],
    price: (monthly: string, yearly: string) => `在美國為每月 ${monthly} 或每年 ${yearly}。`,
    vary: "價格依國家或地區而異。",
    fine: "讀取失敗不會用掉掃描次數，再次掃描同一張照片也不會重複計算。",
  },
  faq: {
    title: "常見問題，一次[[解答]]。",
    items: [
      {
        q: "朋友需要 Splitea 或 iPhone 嗎？",
        a: "不需要。你的連結可以在任何瀏覽器中打開，Android 手機和筆電也可以，不需要 App，也不需要帳戶。頁面提供 10 種語言，朋友用自己的付款 App 付款即可。",
      },
      {
        q: "我需要帳戶嗎？",
        a: "需要。你要使用 Apple 登入才能掃描和分享，Splitea 也會要求取用聯絡人，讓你選擇分帳的對象。完整或有限的取用權限都可以。",
      },
      {
        q: "不訂閱可以做什麼？",
        a: "已經有的收據，什麼都能做。分享連結、即時編輯、結清、資料夾、PDF 匯出和貨幣換算都不需要訂閱，朋友傳給你的分帳也一樣。用完 3 次免費掃描後，無論是用相機、照片、PDF、分享表單還是手動輸入，新增收據都需要 Splitea Unlimited，訂閱後也能自訂強調色。",
      },
      {
        q: "Splitea 會經手金錢嗎？",
        a: "不會。Splitea 從不轉移任何款項，只會打開朋友的付款 App 或連結：視你所在的國家或地區而定，可能是 Venmo、Cash App、PayPal、ATH Móvil、Revolut、Monzo 或 Google Pay UPI。除了 ATH Móvil 需要朋友自行輸入金額，其他都會自動帶入金額。不支援 Apple Pay、Apple Cash 和 Zelle，但朋友仍然可以把自己的份額標記為已付。",
      },
      {
        q: "收據讀錯了怎麼辦？",
        a: "Splitea 會將小計、稅額和總額與收據上印的數字核對，不一致時會提醒你。點一下任何項目，就能修改描述、價格或稅率。如果照片有反光或模糊、收據被截斷、拍到的是菜單而不是帳單，或一張照片裡有好幾張收據，相機也會提醒你。",
      },
      {
        q: "在美國以外也能用嗎？",
        a: "可以。Splitea 已在許多國家或地區的 App Store 上架，包括英國、墨西哥、日本、德國、印度、巴西和韓國。它會用收據上的貨幣分帳，包括日圓、韓元這類沒有「分」的貨幣；也能處理已含稅的收據，例如日本和歐盟的收據；還能把分帳換算成你的貨幣。",
      },
      {
        q: "iOS 27 也能分帳，為什麼還要用 Splitea？",
        a: "Apple 的分帳功能是內建且免費的。它透過 Apple Cash 運作，而 Apple Cash 適用於美國 50 州、華盛頓特區和波多黎各，對象是年滿 18 歲、擁有 iPhone、iPad 或 Apple Watch 的美國居民。使用 Splitea，朋友可以在任何手機或電腦上打開你的連結，用 Venmo、PayPal 或 ATH Móvil 等 App 付款；Splitea 在許多國家或地區都能使用，掃描也不需要 Apple Intelligence。每位朋友都能即時挑選自己的項目，每個項目都套用當地稅率，一趟旅行的收據也能匯總成一份 PDF。Splitea 提供 3 次免費掃描，之後需要訂閱。",
      },
      {
        q: "分享連結可以用多久？",
        a: "分享連結會在建立 30 天後失效。你自己的副本會保留在你的收據庫中。",
      },
      {
        q: "哪些 iPhone 可以使用？",
        a: "任何搭載 iOS 26 或以上版本的 iPhone 都可以。目前沒有 iPad、Mac 或 Android 版 App，使用其他裝置的朋友可以在瀏覽器中打開連結。",
      },
    ],
    dataQ: "我的資料存放在哪裡？",
    dataBefore: "已儲存的收據、資料夾和你的個人檔案會透過你自己的 iCloud 同步。上方的",
    dataLink: "隱私權區塊",
    dataAfter: "列出了哪些資料會傳送到 Splitea 的伺服器，以及會保留多久。",
  },
  get: {
    pronunciation: "/ spli·TE·a /",
    title: "每張收據，[[一點]]即達。",
    body: "你儲存的每一筆分帳都會留在收據庫中，並透過你自己的 iCloud 同步。打開任何一筆，就能看到誰已經付款。",
    small: "免費下載，含 3 次免費掃描。僅限 iPhone，需要 iOS 26 或以上版本。",
    qrCaption: "正在用電腦？用 iPhone 相機掃描。",
    tagline: "Splitea · 帳單，搞定",
    gridAlt: "「所有分帳」收據庫。",
    listAlt: "以列表顯示的「所有分帳」收據庫。",
  },
  footer: {
    origin: "Splitea · 波多黎各製造",
    languages: "語言",
    privacy: "隱私權",
    terms: "條款",
    appStore: "App Store",
    legal: [
      "Apple、Apple 標誌、iPhone、iPad、Mac、Apple Watch、iCloud、Safari、Apple Pay、Apple Cash 和 Apple Intelligence 是 Apple Inc. 在美國及其他國家和地區註冊的商標。App Store 是 Apple Inc. 的服務標誌。",
      "Venmo、Cash App、PayPal、ATH Móvil、Revolut、Monzo、Google Pay、Gemini、Android、WhatsApp 和 Zelle 是其各自所有者的商標。Splitea 與這些公司並無關聯。",
      "© 2026 Raúl Mora.",
    ],
  },
  badgeLabel: "在 App Store 下載 Splitea",
};

export default zhHant;
